/**
 * EN/ES label dictionary for the Floor Manager, registered on the shared
 * i18n layer so `data-i18n*` attributes and manual `t()` calls both read
 * from one source. Values under the legacy hourly-entry keys are carried
 * over VERBATIM by key (index.js:121-347) except the five noted below,
 * which v3's wording replaces; the printer/tutorial/step-guide/instrument
 * keys that page carried are dropped — this page has no printer, no
 * barcode scanner, and no step-by-step tutorial mode.
 */

export const LABELS = {
  en: {
    // -- carried over unchanged from index.js:121-347 --
    floorManager: 'Floor Manager',
    today: 'Today',
    target: 'Target',
    hoursLogged: 'hrs logged',
    line1: '',
    buckers: 'Buckers',
    trimmers: 'Trimmers',
    tzero: 'T-Zero',
    qcperson: 'QC',
    cultivar: 'Cultivar',
    queueNow: 'Now trimming',
    queueNext: 'Next up',
    queueClear: 'Queue is clear',
    queueInQueue: 'in queue',
    queueAll: 'all',
    queueReady: 'ready',
    orderQueue: 'Order Queue',
    qtDone: 'done',
    qtLeft: 'lb left',
    qtNow: 'now',
    qtOrderDone: 'order done',
    done_lbs: 'pounds done',
    err_below_trimmed: 'Already trimmed on the floor:',
    err_above_ordered: 'More than the line ordered:',
    err_save_credit: 'Could not save — try again',
    err_password_needed: 'Operations password needed to change this',
    queueUnavailable: 'Queue unavailable',
    moreOnBoard: 'more on the board',
    saved: 'Saved',
    saveFailed: 'Save failed',
    startDay: 'Start Day',
    setStartTime: 'Set Start Time',
    bagTimer: 'Bag Timer',
    inventory: 'Inventory',
    currentPool: 'Current Pool',
    updatePool: 'Update Pool',
    add: 'Add',
    subtract: 'Subtract',
    set: 'Set',
    optionalNote: 'Optional note...',
    previous: 'Previous',
    current: 'Current',
    newValue: 'New',
    preview: 'Preview',
    adding: 'Adding',
    subtracting: 'Subtracting',
    setting: 'Setting to',
    quickAdd: 'Quick Add',
    quickAddNote10lb: 'Added by 10lb button',
    quickAddNote5kg: 'Added by 5kg button',
    recentChanges: 'Recent Changes',
    noChangesYet: 'No changes yet',
    updating: 'Updating...',
    added: 'Added:',
    subtracted: 'Subtracted:',
    changed: 'Changed:',
    onBreak: 'On Break',

    // -- v3 wording replaces the legacy value (see header) --
    tops: 'Tops',
    smalls: 'Smalls',
    started: 'started',
    saving: 'Saving…',
    line2: 'Line 2',

    // -- new for the floor rebuild --
    now: 'now',
    prevHour: 'Previous hour (←)',
    nextHour: 'Next hour (→)',
    lbTops: 'lb tops',
    targetWord: 'target',
    trimmersShort: 'trimmers',
    notes: 'Notes',
    retry: 'Retry',
    notSaved: 'Not saved',
    enterSaves: 'saves',
    // The shared topbar's connection pill, written by main.js's version poll.
    // The ledger's own words: the column chart's key, and the save it offers.
    smallsShort: 'sm',
    ringWeight: 'Weight on the scale',
    ringTime: 'Time gone',
    legendTops: 'Tops logged',
    legendTarget: 'Target for the hour',
    legendSmalls: 'Smalls are listed under each hour',
    legendPick: 'Click an hour, or use the arrow keys',
    saveHour: 'Save hour',
    statusLive: 'Live',
    statusOffline: 'Offline · retrying',
    statusLoading: 'Loading…',
    unsavedHours: '{n} hours not on the server',
    pace: 'Pace',
    behindPace: 'behind pace',
    aheadPace: 'ahead of pace',
    onPace: 'on pace',
    projected: 'projected',
    left: 'left',
    overtime: 'over',
    elapsedWord: 'elapsed',
    shiftEnded: 'shift ended',
    notStarted: 'not started',
    lastBag: 'last bag',
    emptyHour: 'Nothing entered yet',
    noGoalYet: 'No crew logged yet — the target follows the trimmers',
    logBag: 'Log bag',
    logging: 'Logging…',
    logged: 'Logged',
    logFailed: 'Failed — tap to retry',
    bagsTodayWord: 'bags today',
    averaging: 'averaging',
    scale: 'scale',
    scaleOffline: 'offline',
    scaleWindow: 'Scale reads {g} g — expected {min}–{max} g (with bag).',
    scaleOfflineNote: 'Scale offline — logging without a weight check.',
    drawerTitle: 'Inventory · Order queue',
    open: 'open',
    close: 'Close',
    selectCultivar: 'Select cultivar…',
    addLine2: 'Line 2',
    removeLine2: 'Remove line 2',
    changeDate: 'Change date',
    theme: 'Switch theme',
    language: 'Language',
    noData: 'no data',
    noCultivar: 'no cultivar',
    hours: 'Hours',
    refresh: 'Refresh',
    grams: 'g',
    lbs: 'lb',
    errorLoading: 'Could not load',
    fewer: 'fewer',
    more: 'more',
    of: 'of',
  },
  es: {
    // -- carried over unchanged from index.js:121-347 --
    floorManager: 'Gerente de Piso',
    today: 'Hoy',
    target: 'Meta',
    hoursLogged: 'hrs registradas',
    line1: '',
    buckers: 'Buckers',
    trimmers: 'Podadores',
    tzero: 'T-Zero',
    qcperson: 'QC',
    cultivar: 'Cultivar',
    queueNow: 'Podando ahora',
    queueNext: 'Siguiente',
    queueClear: 'No hay pedidos en cola',
    queueInQueue: 'en cola',
    queueAll: 'todos',
    queueReady: 'listo',
    orderQueue: 'Cola de Pedidos',
    qtDone: 'listo',
    qtLeft: 'lb faltan',
    qtNow: 'ahora',
    qtOrderDone: 'pedido listo',
    done_lbs: 'libras hechas',
    err_below_trimmed: 'Ya podado en el piso:',
    err_above_ordered: 'Más de lo pedido en la línea:',
    err_save_credit: 'No se pudo guardar — intente de nuevo',
    err_password_needed: 'Se necesita la contraseña de operaciones',
    queueUnavailable: 'Cola no disponible',
    moreOnBoard: 'más en el tablero',
    saved: 'Guardado',
    saveFailed: 'Error al guardar',
    startDay: 'Iniciar Día',
    setStartTime: 'Establecer Hora de Inicio',
    bagTimer: 'Temporizador',
    inventory: 'Inventario',
    currentPool: 'Pool Actual',
    updatePool: 'Actualizar Pool',
    add: 'Agregar',
    subtract: 'Restar',
    set: 'Establecer',
    optionalNote: 'Nota opcional...',
    previous: 'Anterior',
    current: 'Actual',
    newValue: 'Nuevo',
    preview: 'Vista Previa',
    adding: 'Agregando',
    subtracting: 'Restando',
    setting: 'Estableciendo a',
    quickAdd: 'Agregar Rápido',
    quickAddNote10lb: 'Agregado por botón 10lb',
    quickAddNote5kg: 'Agregado por botón 5kg',
    recentChanges: 'Cambios Recientes',
    noChangesYet: 'Sin cambios aún',
    updating: 'Actualizando...',
    added: 'Agregado:',
    subtracted: 'Restado:',
    changed: 'Cambiado:',
    onBreak: 'En Descanso',

    // -- v3 wording replaces the legacy value (see header) --
    tops: 'Tops',
    smalls: 'Smalls',
    started: 'inició',
    saving: 'Guardando…',
    line2: 'Línea 2',

    // -- new for the floor rebuild --
    now: 'ahora',
    prevHour: 'Hora anterior (←)',
    nextHour: 'Hora siguiente (→)',
    lbTops: 'lb tops',
    targetWord: 'meta',
    trimmersShort: 'podadores',
    notes: 'Notas',
    retry: 'Reintentar',
    notSaved: 'Sin guardar',
    enterSaves: 'guarda',
    smallsShort: 'peq',
    ringWeight: 'Peso en la báscula',
    ringTime: 'Tiempo transcurrido',
    legendTops: 'Tops registrados',
    legendTarget: 'Meta de la hora',
    legendSmalls: 'Los pequeños se listan bajo cada hora',
    legendPick: 'Haz clic en una hora, o usa las flechas',
    saveHour: 'Guardar hora',
    statusLive: 'En vivo',
    statusOffline: 'Sin conexión · reintentando',
    statusLoading: 'Cargando…',
    unsavedHours: '{n} horas sin guardar en el servidor',
    pace: 'Ritmo',
    behindPace: 'atrás del ritmo',
    aheadPace: 'adelante del ritmo',
    onPace: 'al ritmo',
    projected: 'proyectado',
    left: 'restante',
    overtime: 'excedido',
    elapsedWord: 'transcurrido',
    shiftEnded: 'turno terminado',
    notStarted: 'sin iniciar',
    lastBag: 'última bolsa',
    emptyHour: 'Nada registrado aún',
    noGoalYet: 'Sin equipo registrado aún — la meta sigue a los podadores',
    logBag: 'Registrar bolsa',
    logging: 'Registrando…',
    logged: 'Registrada',
    logFailed: 'Falló — toca para reintentar',
    bagsTodayWord: 'bolsas hoy',
    averaging: 'promedio',
    scale: 'báscula',
    scaleOffline: 'desconectada',
    scaleWindow: 'La báscula marca {g} g — se esperaban {min}–{max} g (con bolsa).',
    scaleOfflineNote: 'Báscula desconectada — se registra sin verificar peso.',
    drawerTitle: 'Inventario · Cola de pedidos',
    open: 'abiertos',
    close: 'Cerrar',
    selectCultivar: 'Seleccionar cultivar…',
    addLine2: 'Línea 2',
    removeLine2: 'Quitar línea 2',
    changeDate: 'Cambiar fecha',
    theme: 'Cambiar tema',
    language: 'Idioma',
    noData: 'sin datos',
    noCultivar: 'sin cultivar',
    hours: 'Horas',
    refresh: 'Actualizar',
    grams: 'g',
    lbs: 'lb',
    errorLoading: 'No se pudo cargar',
    fewer: 'menos',
    more: 'más',
    of: 'de',
  },
};

// shared/i18n.js is a browser module: it reads localStorage at import time and
// src/js/shared/ carries no package.json "type", so Node parses it as CommonJS
// and a static import cannot load in the test runner. The browser gets the
// shared layer (data-i18n walking, ro-lang persistence, the ro:langchange
// event); Node gets a shim with the same surface so the dictionary itself stays
// testable. Top-level await keeps the export surface synchronous for importers.
const shared = typeof window !== 'undefined' ? await import('../shared/i18n.js') : null;
let nodeLang = 'en';

function t(key) {
  if (shared) return shared.t(key);
  return LABELS[nodeLang]?.[key] ?? LABELS.en[key] ?? key;
}
function setLang(lang) {
  if (shared) { shared.setLang(lang); return; }
  nodeLang = lang === 'es' ? 'es' : 'en';
}
function getLang() { return shared ? shared.getLang() : nodeLang; }
function toggleLang() { setLang(getLang() === 'en' ? 'es' : 'en'); }

if (shared) shared.registerLabels(LABELS);

export { t, setLang, getLang, toggleLang };
