/**
 * Tag & Desk — the views. Ported from the reviewed prototype onto the live
 * model (model.js), the API (api.js) and desk memory (store.js).
 * Every write goes: API call → reload() → render(). Desk memory writes go:
 * mutate L → saveL() → render().
 */
import { t, ES } from './labels.js';
import * as api from './api.js';
import { addDays, daysBetween, localDay, d1Instant, cardState, expectedOf, leadOf, orderedMap, toRawCard, ZONES, ulinePasteText, ulineQuickOrderUrl, ULINE_HELPER_URL, ULINE_BOOKMARKLET, amazonQueueUrl, walmartCartUrl } from './model.js';

// ---------- context (set by init) ----------
let M = null, L = null, saveL = () => {}, reload = async () => {}, RAW = {}, PAGE_URL = '';
export const S = { view: 'order', filter: 'all', vendor: '', zone: '', q: '', sel: 'Uline', showNext: false, printFmt: 'card', printSel: null, tag: { state: 'queued', card: null, qty: null, undoLeft: 30, last: 'scan', lang: null, told: {}, live: false, added: false } };

export function init(ctx) { M = ctx.M; L = ctx.L; saveL = ctx.saveL; reload = ctx.reload; RAW = ctx.RAW; PAGE_URL = ctx.pageUrl; if (!S.printSel) S.printSel = M.cards[0]?.id || null; if (!S.tag.card) S.tag.card = M.cards[0]?.id || null; if (!M.vendors[S.sel]) S.sel = Object.keys(M.vendors).find(v => M.vendors[v].lane === 'cart') || 'Uline'; }
export function setModel(m, raw) { M = m; RAW = raw || RAW; }

// ---------- helpers ----------
const $ = (s, r = document) => r.querySelector(s), $$ = (s, r = document) => [...r.querySelectorAll(s)];
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const DOW = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const DOW_ES = ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'], MON_ES = ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'];
const pd = s => { const [y, m, d] = String(s).slice(0, 10).split('-').map(Number); return new Date(y, m - 1, d); };
const fmtD = (s, es = ES()) => { if (!s) return '—'; const d = pd(s); return es ? `${DOW_ES[d.getDay()]} ${d.getDate()} ${MON_ES[d.getMonth()]}` : `${DOW[d.getDay()]} ${MON[d.getMonth()]} ${d.getDate()}`; };
const fmtMD = (s, es = ES()) => { if (!s) return '—'; const d = pd(s); return es ? `${d.getDate()} ${MON_ES[d.getMonth()]}` : `${MON[d.getMonth()]} ${d.getDate()}`; };
const fmtTS = (s, es = ES()) => { const d = d1Instant(s); if (!d || Number.isNaN(d.getTime())) return '—'; try { return d.toLocaleString(es ? 'es-MX' : 'en-US', { timeZone: 'America/Los_Angeles', weekday: 'short', hour: 'numeric', minute: '2-digit' }).replace(',', '').replace(/\s?([AP]M)/, m => m.toLowerCase()).replace(/\s?p\.\s?m\./, ' pm').replace(/\s?a\.\s?m\./, ' am'); } catch { return d.toISOString(); } };
const nowISO = () => new Date().toISOString().slice(0, 19).replace('T', ' ');
const daysSince = s => daysBetween(s, M.today);
const money = n => n == null ? '—' : '$' + n.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
const cards = () => M.cards, byId = id => M.byId[id];
const PLACEHOLDER = 'data:image/svg+xml;utf8,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="6" fill="#e8e4de"/><path d="M10 28l7-9 5 6 4-4 4 7z" fill="#b8b3a8"/></svg>');
const THUMB = c => c.picture || PLACEHOLDER;
const vendorCards = v => cards().filter(c => c.vendor === v);
const DAY_VENDORS = () => Object.keys(M.vendors).filter(v => M.vendors[v].lane === 'cart' && v !== 'Sticker Mule' && v !== '(Unspecified)').sort((a, b) => (['Uline', 'Amazon', 'Walmart'].indexOf(a) + 1 || 99) - (['Uline', 'Amazon', 'Walmart'].indexOf(b) + 1 || 99));
const Lslice = () => ({ ordered: orderedMap(L.receipts), groveOrdered: L.groveOrdered, backorder: L.backorder, out: outMap(), dismissed: L.dismissed, received: L.received });
function outMap() { const m = {}; for (const c of cards()) if (c.inCart && c.redCard && !L.outAck[c.inCart.cartId]) m[c.id] = { at: c.inCart.addedAt, cartId: c.inCart.cartId }; return m; }
const state = c => cardState(c, M, Lslice());
const vendorLead = v => { const ls = vendorCards(v).map(leadOf).sort((a, b) => a - b); return ls.length ? ls[ls.length >> 1] : 1; };

// variant-first naming
function variant(c) { const s = c.item; let m;
  if (/nitrile/i.test(s)) { m = s.match(/\b(Large|Medium|Small)\b/i); if (m) return { badge: m[1][0].toUpperCase(), lead: m[1][0].toUpperCase() + m[1].slice(1).toLowerCase(), rest: 'Nitrile gloves' }; }
  if (c.vendor === 'Grove') { if (/1 ?oz/i.test(s)) return { badge: '1 oz', lead: '1 oz', rest: 'Custom bags' }; if (/10 ?lb/i.test(s)) return { badge: '10 lb', lead: '10 lb', rest: 'Grove bags' }; if (/blank/i.test(s)) return { badge: 'blank', lead: '1 lb', rest: 'Blank bags' }; if (/1 ?lb/i.test(s)) return { badge: '1 lb', lead: '1 lb', rest: 'Custom bags' }; if (/1\/4/.test(s)) return { badge: '¼–½', lead: '¼ & ½ lb', rest: 'Custom bags' }; }
  if (/sticker/i.test(s)) { m = s.match(/\(([^)]+)\)/); if (m) return { badge: m[1].split(' ')[0], lead: m[1], rest: s.replace(/\s*\([^)]*\)/, '') }; }
  m = s.match(/^(\d+x\d+(?:x\d+)?)\s*\(([^)]+)\)/i); if (m) return { badge: m[2].replace(/\s*box/i, '').trim(), lead: m[2].replace(/\s*box/i, '').trim() + ' box', rest: m[1] };
  return { badge: null, lead: null, rest: s }; }
const NAME_ES = { 'Nitrile gloves': 'Guantes de nitrilo', 'Custom bags': 'Bolsas personalizadas', 'Grove bags': 'Bolsas Grove', 'Blank bags': 'Bolsas lisas', Large: 'Grande', Medium: 'Mediano', Small: 'Chico' };
function variantL(c, forceLang) { const v = { ...variant(c) }; const es = forceLang ? forceLang === 'es' : ES(); if (!es) return v; if (v.rest && NAME_ES[v.rest]) v.rest = NAME_ES[v.rest]; if (v.lead) { if (NAME_ES[v.lead]) v.lead = NAME_ES[v.lead]; else if (/ box$/.test(v.lead)) v.lead = v.lead.replace(/ box$/, ' caja'); } return v; }
function nameHtml(c, fl) { const v = variantL(c, fl); return v.lead ? `<b>${esc(v.lead)}</b> · ${esc(v.rest)}` : esc(v.rest); }
function shortName(c, fl) { const v = variantL(c, fl); return v.lead ? `${v.lead} ${v.rest}` : v.rest; }
function picHtml(c) { const v = variant(c); return `<div class="pic"><img src="${esc(THUMB(c))}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src='${PLACEHOLDER}'">${v.badge ? `<span class="vb">${esc(v.badge)}</span>` : ''}</div>`; }
const UNITS = { each: [['unit', 'units'], ['unidad', 'unidades']], pack: [['pack', 'packs'], ['paquete', 'paquetes']], case: [['case', 'cases'], ['caja grande', 'cajas grandes']], box: [['box', 'boxes'], ['caja', 'cajas']], roll: [['roll', 'rolls'], ['rollo', 'rollos']] };
function unitOf(c, q, forceLang) { const es = forceLang ? forceLang === 'es' : ES(); const one = q === 1; const u = L.prefs[c.id]?.unit; if (u && UNITS[u]) return UNITS[u][es ? 1 : 0][one ? 0 : 1]; if (c.packSize) return es ? (one ? 'caja' : 'cajas') : (one ? 'box' : 'boxes'); if (/glove|box/i.test(c.item) && c.vendor === 'Uline') return es ? (one ? 'caja' : 'cajas') : (one ? 'box' : 'boxes'); if (/sticker/i.test(c.item)) return es ? (one ? 'etiqueta' : 'etiquetas') : (one ? 'sticker' : 'stickers'); if (/tape/i.test(c.item)) return es ? (one ? 'rollo' : 'rollos') : (one ? 'roll' : 'rolls'); if (/rag/i.test(c.item)) return es ? (one ? 'paquete' : 'paquetes') : (one ? 'pack' : 'packs'); return es ? (one ? 'unidad' : 'unidades') : (one ? 'unit' : 'units'); }
function gapTxt(c) { if (!c.medianGap) return ''; const g = Math.round(c.medianGap); if (g <= 8) return ES() ? 'casi cada semana' : 'about weekly'; if (g <= 16) return ES() ? 'cada dos semanas' : 'about every 2 weeks'; return ES() ? `cada ~${g} días` : `about every ${g} days`; }
function reason(c, q) { q = q ?? c.suggested; if (c.numericLevels && c.fill && c.reorder != null && c.fill > c.reorder) { if (q === c.suggested) return ES() ? `${q} lo devuelve a lleno (${c.fill | 0})` : `${q} brings it back to full (${c.fill | 0})`; return ES() ? `La tarjeta sugiere ${c.suggested} para llenar a ${c.fill | 0}` : `Card suggests ${c.suggested} to fill to ${c.fill | 0}`; } return ES() ? `La tarjeta dice ${esc(c.orderQtyRaw)}` : `The card says ${esc(c.orderQtyRaw)}`; }
function isLate(c) { return !!(c.expected && daysSince(c.expected) > 0); }
function evidence(c) { const st = state(c), es = ES();
  if (st === 'queued') { const r = c.inCart; const who = r.addedBy && /desk/.test(r.addedBy) ? (es ? 'Agregado desde el escritorio' : 'Added from the desk') : `${t('scanned')} ${c.scanCount}×`; return `<span class="p">${who}</span><span class="sep">·</span><span class="p">${fmtTS(r.addedAt)}</span>`; }
  if (st === 'on-order') { const g = L.groveOrdered[c.id]; if (g) return `<b>${t('orderedWithDamon', { d: fmtMD(g.expected) })}</b>`; const rc = L.receipts[orderedMap(L.receipts)[c.id]]; const late = rc && M.today > rc.expected; return es ? `<b>En camino</b> · ${late ? `<span class="warn">se esperaba el ${fmtD(rc.expected)}</span>` : `llega ${rc ? fmtD(rc.expected) : ''}`}` : `<b>On order</b> · ${late ? `<span class="warn">was due ${fmtD(rc.expected)}</span>` : `arrives ${rc ? fmtD(rc.expected) : ''}`}`; }
  if (st === 'requested') { const rq = c.openRequest || {}; const n = rq.requestedAt ? daysSince(localDay(rq.requestedAt)) : 0; const warn = n > 7; return `<span class="p ${warn ? 'warn' : ''}">${es ? `Solicitado a Damon el <b>${fmtMD(localDay(rq.requestedAt))}</b>` : `Requested from Damon <b>${fmtMD(localDay(rq.requestedAt))}</b>`}</span><span class="sep">·</span><span class="p ${warn ? 'warn' : ''}">${warn ? (es ? `${n} días sin confirmación` : `${n} days waiting — no confirmation`) : (es ? `${n} ${n === 1 ? 'día' : 'días'} esperando` : `${n} day${n === 1 ? '' : 's'} waiting`)}</span>${rq.notifyState === 'failed' ? `<span class="sep">·</span><span class="p warn">${es ? 'el correo no salió' : 'email failed'}</span>` : ''}`; }
  if (L.received[c.id] && !['queued', 'on-order'].includes(st)) { const e = expectedOf(c, M, Lslice()); return es ? `<b>Recibido ${fmtMD(L.received[c.id])}</b>${e ? ` · se espera ~${fmtMD(e)}` : ''}` : `<b>Received ${fmtMD(L.received[c.id])}</b>${e ? ` · expected ~${fmtMD(e)}` : ''}`; }
  if (st === 'check') return es ? `<b>${daysSince(c.lastOrderDay)} días</b> sin pedido (último ${fmtMD(c.lastOrderDay)}) · antes ${gapTxt(c)}${c.levelsChanged ? ` · niveles cambiados ${fmtMD(c.levelsChanged)}` : ''}` : `<b>${daysSince(c.lastOrderDay)} days</b> without an order (last ${fmtMD(c.lastOrderDay)}) · used to be ${gapTxt(c)}${c.levelsChanged ? ` · levels changed ${fmtMD(c.levelsChanged)}` : ''}`;
  if (c.expected) { const late = daysSince(c.expected); const when = late > 0 ? `<b>${t('overdue', { d: fmtMD(c.expected) })}</b> · ${late} d` : `${t('expected', { d: `<b>${fmtMD(c.expected)}</b>` })}`; return `${when} · ${c.n} ${t('orders')}, ${gapTxt(c)}`; }
  if (c.n > 0) return es ? `Último pedido <b>${fmtMD(c.lastOrderDay)}</b> · ${c.n} ${c.n === 1 ? 'pedido' : 'pedidos'}` : `Last ordered <b>${fmtMD(c.lastOrderDay)}</b> · ${c.n} order${c.n === 1 ? '' : 's'}`;
  return es ? 'Nunca pedido por la app' : 'Never ordered through the app'; }
function earlyFlag(c) { const r = c.inCart; if (!r || !c.expected || !c.medianGap) return ''; const early = (pd(c.expected) - pd(localDay(r.addedAt))) / 86400000; if (early > 0.5 * c.medianGap) return `<span class="flag early">${ES() ? 'Escaneo temprano' : 'Scanned early'} · ${ES() ? 'se esperaba' : 'expected'} ~${fmtMD(c.expected)}</span>`; return ''; }
function priceTxt(c, q) { if (c.unitPrice == null) return c.priceRaw ? `<span class="p">${t('unpriced')} (${esc(c.priceRaw)})</span>` : ''; return `<span class="p">${money(c.unitPrice * q)}</span>`; }
function lineEst(c, q) { return c.unitPrice == null ? null : c.unitPrice * q; }
function slotTxt(c) { if (c.zone === 'Fulfillment') return 'FULFILLMENT'; return c.slot ? `${c.zone.toUpperCase()} · ${c.slot}` : c.zone.toUpperCase(); }
function slotChip(c) { if (c.zone === 'Unassigned') return `<span class="chipm gap">${ES() ? 'sin lugar en el estante' : 'no shelf spot'}</span>`; return `<span class="chipm slot">${esc(slotTxt(c))}</span>`; }
function meta(parts) { return parts.filter(Boolean).join('<span class="sep">·</span>'); }
const bySlot = (a, b) => (a.zone || '').localeCompare(b.zone || '') || (a.slot || 'zz').localeCompare(b.slot || 'zz', undefined, { numeric: true }) || a.item.localeCompare(b.item);

// ---------- toast ----------
let toastTimer = null;
export function toast(msg, undo) { const host = $('#toasts'); if (!host) return; host.innerHTML = ''; clearTimeout(toastTimer); const el = document.createElement('div'); el.className = 'toast'; el.innerHTML = `<span>${msg}</span>${undo ? `<button>${t('undo')}</button>` : ''}`; if (undo) el.querySelector('button').onclick = () => { undo(); el.remove(); }; host.appendChild(el); toastTimer = setTimeout(() => el.remove(), undo ? 8000 : 4000); }
async function act(fn, ok, undo) { try { await fn(); await reload(); render(); if (ok) toast(ok, undo); } catch (e) { console.error(e); toast(`${t('saveFail')} · ${esc(e.message || '')}`); render(); } }

// ---------- summaries ----------
function summary(v) { const vc = vendorCards(v); const dueKey = c => outMap()[c.id] ? '0' : (L.backorder[c.id] ? '1' : (c.expected || '9'));
  const q = vc.filter(c => state(c) === 'queued'), due = vc.filter(c => state(c) === 'due').sort((a, b) => dueKey(a).localeCompare(dueKey(b))), chk = vc.filter(c => state(c) === 'check'), next = vc.filter(c => state(c) === 'due-next').sort((a, b) => (a.expected || '9').localeCompare(b.expected || '9')), req = vc.filter(c => state(c) === 'requested'), on = vc.filter(c => state(c) === 'on-order');
  let est = 0, unp = 0; q.forEach(c => { const e = lineEst(c, c.inCart.qty); if (e == null) unp++; else est += e; });
  const todo = v === 'Sticker Mule' ? q.length + due.length + next.length : (v === 'Grove' ? req.length : q.length + due.length + chk.length);
  return { q, due, chk, next, req, on, est, unp, todo }; }
function lateReceipts() { return Object.values(L.receipts).filter(r => M.today > r.expected && r.open.length).length; }
function counts() { const day = DAY_VENDORS().reduce((a, v) => a + summary(v).todo, 0); const sm = M.vendors['Sticker Mule'] ? summary('Sticker Mule') : { todo: 0 }; const gr = M.vendors.Grove ? summary('Grove') : { req: [] }; return { order: day + sm.todo + gr.req.length + lateReceipts(), cards: cards().length, print: cards().filter(c => !L.printed[c.id]).length, grove: gr.req.length, tag: '' }; }

// ---------- tabs ----------
const ICONS = { order: '<path d="M3 4h2l2 9h9l2-6H6"/><circle cx="8" cy="16" r="1.2"/><circle cx="15" cy="16" r="1.2"/>', cards: '<rect x="3" y="3" width="6" height="6" rx="1"/><rect x="11" y="3" width="6" height="6" rx="1"/><rect x="3" y="11" width="6" height="6" rx="1"/><rect x="11" y="11" width="6" height="6" rx="1"/>', print: '<path d="M6 7V3h8v4M4 7h12v7h-3v3H7v-3H4z"/>', grove: '<path d="M5 7h10l1 10H4z"/><path d="M7 7a3 3 0 0 1 6 0"/>', tag: '<rect x="6" y="2" width="8" height="16" rx="2"/><path d="M9 15h2"/>' };
const VIEWS = ['order', 'cards', 'print', 'grove', 'tag'];
function renderTabs() { const c = counts();
  $('#tabs').innerHTML = VIEWS.map(k => `<button class="tab" role="tab" aria-selected="${S.view === k}" data-view="${k}">${t(k)}${c[k] !== '' ? `<span class="n">${c[k]}</span>` : ''}</button>`).join('');
  $('#bottombar').innerHTML = ['order', 'cards', 'grove', 'print', 'tag'].map(k => `<button role="tab" aria-selected="${S.view === k}" data-view="${k}"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${ICONS[k]}</svg>${t(k)}</button>`).join('');
  $$('[data-view]').forEach(b => b.onclick = () => { S.view = b.dataset.view; $('#toasts').innerHTML = ''; document.body.classList.remove('nav-open'); render(); window.scrollTo(0, 0); });
  $$('[data-t]').forEach(el => el.textContent = t(el.dataset.t));
  $('#langBtn').textContent = ES() ? 'EN' : 'ES'; $('#railLang').textContent = ES() ? 'English' : 'Español'; $('#railTheme').textContent = ES() ? 'Oscuro / Claro' : 'Dark / Light'; $('#railAdd').textContent = '+ ' + t('addCard');
  const d = pd(M.today); $('#todayLbl').textContent = ES() ? `${DOW_ES[d.getDay()]} ${d.getDate()} ${MON_ES[d.getMonth()]}` : `${DOW[d.getDay()]} · ${MON[d.getMonth()]} ${d.getDate()}`;
  $('#q').placeholder = ES() ? 'Buscar tarjetas…' : 'Search cards…'; }

// ---------- ORDER ----------
function vtile(v, label, big, line, pressed, zero, attr) { return `<button class="vt ${zero ? 'zero' : ''}" aria-pressed="${pressed}" ${attr || ''}><span class="vn">${esc(label)}</span><span class="big">${big}</span><span class="vl">${line}</span></button>`; }
function outBar() { const es = ES(); const om = outMap(); const ids = Object.keys(om).map(Number); if (!ids.length) return '';
  return ids.map(id => { const c = byId(id); const o = om[id]; const st = state(c); const act = st === 'queued' ? `<span class="chipm">${es ? 'en la lista' : 'on the list'} · ×${c.inCart.qty}</span>` : (st === 'on-order' ? `<span class="chipm">${t('onOrder')}</span>` : `<button class="tb-btn btn-amber" data-add="${id}">${t('add')} ${c.suggested} → ${esc(c.vendor)}</button>`);
    return `<div class="outbar" data-outid="${id}"><span class="ox">!</span><div><b>${t('outHead', { i: shortName(c) })}</b><p>${t('outSub', { t: fmtTS(o.at) })}</p></div><span class="oacts">${act}<button class="tb-btn" data-outclear="${o.cartId}">${t('outClear')}</button></span></div>`; }).join(''); }
function renderOrder() { const es = ES(); const el = $('#view-order');
  const dayVendors = DAY_VENDORS().filter(v => ['Uline', 'Amazon', 'Walmart'].includes(v) || summary(v).todo > 0 || L.receipts[v]);
  let h = outBar() + `<div class="vstrip">`;
  const dayItems = dayVendors.reduce((a, v) => { const s = summary(v); return a + s.q.length + s.due.length; }, 0), dayEst = dayVendors.reduce((a, v) => a + summary(v).est, 0), placed = dayVendors.filter(v => L.receipts[v] && L.receipts[v].open.length).length;
  const dayLine = dayItems ? ` · ${dayItems} ${t('toReview')}${dayEst > 0 ? ` · ≈ ${money(dayEst)}` : ''}` : (placed ? ` · ${placed} ${es ? (placed === 1 ? 'pedido hecho' : 'pedidos hechos') : (placed === 1 ? 'order placed' : 'orders placed')}` : '');
  const tom = M.d1 === addDays(M.today, 1);
  h += `<div class="vwell now"><span class="eyebrow"><b>${fmtD(M.d1)}</b> · ${tom ? t('tomorrow') : (es ? 'próxima revisión' : 'next check')}${tom ? ` · ${es ? 'próxima revisión' : 'next check'}` : ''}${dayLine}</span><div class="vts">${dayVendors.map(v => { const s = summary(v); const rc = L.receipts[v]; const open = rc && rc.open.length ? rc : null; const pending = s.q.length + s.due.length; const late = open && M.today > open.expected; let big, line;
    if (open && pending === 0) { big = late ? `!<small>${t('lateShort')}</small>` : `✓<small>${t('ordered').toLowerCase()}</small>`; line = `${open.n} ${t('items')} · ${late ? (es ? 'se esperaba el' : 'was due') : t('arrives')} ${fmtMD(open.expected)}${s.chk.length ? ` · ${s.chk.length} ${t('toCheck')}` : ''}`; }
    else if (s.todo > 0) { big = `${pending || s.todo}<small>${t('toReview')}</small>`; line = open ? `✓ ${open.n} ${t('ordered').toLowerCase()} · ${t('arrives')} ${fmtMD(open.expected)}` : [s.q.length ? `${s.q.length} ${t('queued').toLowerCase()}` : '', s.est > 0 ? `≈ ${money(s.est)}` : (s.unp ? `${s.unp} ${es ? 'sin precio' : 'unpriced'}` : '')].filter(Boolean).join(' · '); }
    else { big = `✓<small>${t('allSet')}</small>`; line = es ? 'nada que pedir' : 'nothing to order'; }
    return vtile(v, v, big, line, S.sel === v, s.todo === 0 && !late, `data-v="${esc(v)}"`); }).join('')}</div></div>`;
  if (M.vendors['Sticker Mule']) { const sm = summary('Sticker Mule'); const smr = L.receipts['Sticker Mule']; const smo = smr && smr.open.length ? smr : null;
    h += `<div class="vwell"><span class="eyebrow">${t('whenTriggered')}</span><div class="vts">${vtile('Sticker Mule', 'Sticker Mule', sm.todo ? `${sm.todo}<small>${t('runningOut')}</small>` : (smo ? `✓<small>${t('ordered').toLowerCase()}</small>` : `✓<small>${t('allSet')}</small>`), smo && !sm.todo ? `${smo.n} ${t('items')} · ${t('arrives')} ${fmtMD(smo.expected)}` : t('allThree'), S.sel === 'Sticker Mule', sm.todo === 0, `data-v="Sticker Mule"`)}</div></div>`; }
  if (M.vendors.Grove) { const gr = summary('Grove'); h += `<div class="vwell"><span class="eyebrow">${t('byEmail')}</span><div class="vts">${vtile('Grove', 'Grove', `${gr.req.length}<small>${t('withDamon')}</small>`, t('opensGrove'), false, false, `data-go="grove"`)}</div></div>`; }
  h += `</div>`;
  h += renderBoard(S.sel);
  if (M.vendors[S.sel] && M.vendors[S.sel].lane === 'cart' && S.sel !== 'Sticker Mule') { const nx = summary(S.sel).next;
    if (nx.length) { h += `<p class="later">${t(nx.length === 1 ? 'laterOne' : 'later', { n: nx.length, v: S.sel, a: fmtD(M.d2), b: fmtD(M.d3) })}. <button id="toggleNext">${S.showNext ? t('hide') : t('show')}</button></p>`; if (S.showNext) h += `<div class="nextwrap">${lane('n', 4, t('nextLane', { d: fmtD(M.d3) }), nx.length, es ? 'Nadie los escaneó todavía · agrégalos si quieres que vayan en la próxima revisión' : 'Nobody has scanned these yet · add one to ride the next check', nx.map(c => icard(c, 'next')).join(''), `<button class="tb-btn btn-sm" data-addids="${nx.map(c => c.id).join(',')}" data-addv="${esc(S.sel)}">${t('addAll')} ${nx.length}</button>`)}</div>`; }
    else h += `<p class="later muted">${t('laterNone', { v: S.sel, b: fmtD(M.d3) })}.</p>`; }
  h += renderHistory();
  h += `<p class="footnote">${t('deskMemory')}</p>`;
  el.innerHTML = h;
  $$('.vt[data-v]', el).forEach(b => b.onclick = () => { S.sel = b.dataset.v; render(); });
  $$('.vt[data-go]', el).forEach(b => b.onclick = () => { S.view = b.dataset.go; render(); window.scrollTo(0, 0); });
  const tn = $('#toggleNext', el); if (tn) tn.onclick = () => { S.showNext = !S.showNext; render(); };
  const vs = $('.vstrip', el); const updMask = () => vs.classList.toggle('scrollable', vs.scrollLeft + vs.clientWidth < vs.scrollWidth - 2); vs.onscroll = updMask; requestAnimationFrame(updMask);
  wire(el); }
function icard(c, mode) { const es = ES(); const r = c.inCart; let qty = '', acts = '', flags = '', metaLine = '', rs = '', cls = ''; const om = outMap();
  if (mode === 'queued') {
    const w = Math.max(2, String(r.qty).length) + 1.6;
    qty = `<div class="qtyblock"><span class="stepper"><button aria-label="${es ? 'Menos' : 'Fewer'}" data-dec="${c.id}" ${r.qty <= 1 ? 'disabled' : ''}>−</button><input type="number" min="1" value="${r.qty}" style="width:calc(${w}ch + 14px)" data-qty="${c.id}" aria-label="${es ? 'Cantidad' : 'Quantity'}"><button aria-label="${es ? 'Más' : 'More'}" data-inc="${c.id}">+</button></span><span class="qu">${unitOf(c, r.qty)}</span></div>`;
    rs = reason(c, r.qty);
    if (c.scanCount > 1 && c.fill && r.qty > c.suggested && r.qty <= c.fill) flags += `<span class="flag stacked">${es ? `${c.scanCount} escaneos sumaron ${r.qty}` : `${c.scanCount} scans stacked to ${r.qty}`} · <button data-setqty="${c.id}:${c.suggested}">${es ? 'usar' : 'use'} ${c.suggested}</button></span>`;
    else if (c.scanCount > 1) flags += `<span class="flag info">${es ? `Escaneado ${c.scanCount}× — probablemente ${c.scanCount} personas; ${c.suggested} lo llena a ${c.fill | 0}` : `Scanned ${c.scanCount}× — probably ${c.scanCount} people; ${c.suggested} fills it to ${c.fill | 0}`}${r.qty !== c.suggested ? ` · <button data-setqty="${c.id}:${c.suggested}">${es ? 'usar' : 'use'} ${c.suggested}</button>` : ''}</span>`;
    if (c.bumps) flags += `<span class="flag info">+${c.bumps} ${es ? 'desde el piso' : 'from the floor'}</span>`;
    if (om[c.id]) { cls = 'late'; flags += `<span class="flag late">${t('redCard')} · ${fmtTS(om[c.id].at)}</span>`; }
    if (c.urgent) flags += `<span class="flag urgent">${t('urgentFlag', { t: fmtTS(r.addedAt) })}</span>`;
    flags += earlyFlag(c);
    metaLine = meta([evidence(c), priceTxt(c, r.qty)]);
    acts = `<button class="link" data-remove="${c.id}">${t('remove')}</button>`;
  } else if (mode === 'due') {
    const bo = L.backorder[c.id], ou = om[c.id]; cls = (isLate(c) || bo || ou) ? 'late' : ''; qty = `<div class="qtyblock"><span class="qn">${c.suggested}</span><span class="qu">${unitOf(c, c.suggested)}</span></div>`; rs = reason(c);
    if (ou) flags = `<span class="flag late">${t('redCard')} · ${fmtTS(ou.at)}</span>`; else if (bo) flags = `<span class="flag back">${t('backFlag', { d: fmtMD(bo.at) })}</span>`; else if (isLate(c)) flags = `<span class="flag late">${t('overdue', { d: fmtMD(c.expected) })}</span>`;
    metaLine = meta([ou ? (es ? 'Se acabó por completo — pídelo hoy y sube el nivel' : 'Completely out — order it today and raise the level') : bo ? (es ? `Se marcó «no llegó» en el pedido ${esc(bo.vendor)} del ${fmtMD(bo.at)}` : `Marked “not shipped” on the ${esc(bo.vendor)} order of ${fmtMD(bo.at)}`) : (isLate(c) ? `${c.n} ${t('orders')}, ${gapTxt(c)}` : evidence(c)), priceTxt(c, c.suggested)]);
    acts = `<button class="tb-btn btn-amber grow" data-add="${c.id}">${t('add')} ${c.suggested} → ${esc(c.vendor)}</button>`;
  } else if (mode === 'check') {
    qty = `<div class="qtyblock"><span class="qn">${c.suggested}</span><span class="qu">${unitOf(c, c.suggested)}</span></div>`; rs = reason(c); metaLine = meta([evidence(c), priceTxt(c, c.suggested)]);
    acts = `<button class="tb-btn grow" data-dismiss="${c.id}">✓ ${t('stocked', { d: fmtMD(M.d2) })}</button><button class="tb-btn grow" data-add="${c.id}">${t('add')} ${c.suggested}</button>`;
  } else if (mode === 'next') {
    qty = `<div class="qtyblock"><span class="qn">${c.suggested}</span><span class="qu">${unitOf(c, c.suggested)}</span></div>`; rs = reason(c); metaLine = meta([evidence(c), priceTxt(c, c.suggested)]);
    acts = `<button class="tb-btn grow" data-add="${c.id}">${t('add')} ${c.suggested} → ${esc(c.vendor)}</button>`;
  } else if (mode === 'req') {
    const g = L.groveOrdered[c.id]; const rq = c.openRequest || {}; const n = rq.requestedAt ? daysSince(localDay(rq.requestedAt)) : 0; cls = (!g && n > 7) ? 'overdue-req' : ''; metaLine = evidence(c);
    if (g) acts = `<button class="tb-btn btn-primary grow" data-recv="${c.id}">${t('receiveIntoBins')}</button>`;
    else { const asked = L.nudged[c.id] === M.today; const nudge = `<button class="tb-btn grow ${n > 7 && !asked ? 'btn-primary' : ''}" data-nudge="${c.id}" ${asked ? 'disabled' : ''}>${asked ? t('askedToday') : t('askAgain')}</button>`; const markg = `<button class="tb-btn grow hide-m ${n > 7 ? '' : 'btn-primary'}" data-markg="${c.id}">${t('markOrderedG')}</button>`; acts = n > 7 ? nudge + markg : markg + nudge; }
  } else if (mode === 'bin') {
    const b = L.bins[c.id]; const seed = { 21: 600, 54: 450, 56: 350, 69: 90, 99: 90 }[c.id] || 300;
    if (b) { const total = b.total, sealed = b.sealed; const shown = Math.min(total, 12); qty = `<div class="qtyblock"><span class="bins">${Array.from({ length: shown }, (_, i) => `<i class="${i < sealed ? '' : 'off'}"></i>`).join('')}${total > shown ? `<span class="more">+${total - shown}</span>` : ''}</span><span class="qu"><b class="mono">${sealed}</b> ${es ? `de ${total} bins sellados` : `of ${total} bins sealed`}</span></div>`; metaLine = meta([es ? `Recibido ${fmtMD(b.at)} · ${b.perBin} bolsas por bin` : `Received ${fmtMD(b.at)} · ${b.perBin} bags per bin`, b.lot ? `${es ? 'lote' : 'lot'} ${esc(b.lot)}` : '', t('orderWhen')]); }
    else { metaLine = meta([t('noBins', { n: 200 }), t('orderWhen'), es ? `uso estimado ${seed}/mes` : `est. use ${seed}/month`]); }
    acts = `<button class="tb-btn btn-primary grow" data-recv="${c.id}">${t('receiveBins')}</button>`;
  } else if (mode === 'bundle') {
    qty = `<div class="qtyblock"><span class="qn">${c.fill | 0}</span><span class="qu">${unitOf(c, c.fill | 0)}</span></div>`; metaLine = evidence(c);
    acts = `<button class="tb-btn grow" data-add="${c.id}">${t('add')} ${c.fill | 0}</button>`;
  }
  return `<div class="ic ${cls}" data-id="${c.id}"><div class="top">${picHtml(c)}<h4 class="nm">${nameHtml(c)}</h4></div><div class="body"><div class="chips">${slotChip(c)}${c.model ? `<span class="chipm hide-m">${esc(c.model)}</span>` : ''}</div>${qty}${rs ? `<div class="reason">${rs}</div>` : ''}${flags ? `<div class="flags">${flags}</div>` : ''}<div class="meta">${metaLine}</div>${acts ? `<div class="acts">${acts}</div>` : ''}</div></div>`; }
function lane(cls, num, label, n, sub, inner, act, emptyTxt, subClass) { return `<section class="lane ${cls}"><div class="lane-h"><span class="num">${num}</span><span class="lbl">${esc(label)}</span><span class="cnt">${n}</span>${act ? `<span class="act">${act}</span>` : ''}</div><p class="lane-sub ${subClass || ''}">${n ? sub : (emptyTxt || sub)}</p><div class="icards">${inner || `<div class="empty">${emptyTxt || (ES() ? 'Nada aquí' : 'Nothing here')}</div>`}</div></section>`; }
function receiptHtml(v, s) { const es = ES(); const rc = L.receipts[v]; if (!rc || !rc.open.length) return ''; const late = M.today > rc.expected; const lateDays = late ? daysSince(rc.expected) : 0; const undoLeft = Math.max(0, ((rc.undoUntil - Date.now()) / 1e3) | 0); let h = '';
  h += `<div class="receipt"><span class="ok"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="2.4"><path d="M4 10l4 4 8-8"/></svg></span><div><h4>${es ? 'Marcado como pedido' : 'Marked ordered'} — ${esc(v)} · ${rc.n} ${t('items')}${rc.est > 0 ? ` · ${t('est')} ${money(rc.est)}` : ''}</h4><p>${fmtD(rc.day)} ${fmtTS(rc.whenISO).replace(/^\S+\s/, '')} · ${es ? `llega ${fmtD(rc.expected)}. Estas tarjetas dicen «en camino» hasta que toques Recibido — por artículo o todos juntos.` : `arrives ${fmtD(rc.expected)}. These cards read “On order” until you tap Received — per item, or all at once.`}</p></div>${undoLeft > 0 ? `<button class="tb-btn undo" data-undo="${esc(v)}">${t('undo')}</button>` : ''}</div>`;
  h += `<div class="onorder ${late ? 'late' : ''}"><div class="oh"><b>${late ? `<span class="late-txt">${t('lateOrder', { d: fmtD(rc.expected), n: lateDays })}</span>` : t('onOrderArrives', { n: s.on.length, d: fmtD(rc.expected) })}</b>${rc.short.length ? `<span class="muted">· ${rc.short.length} ${t('notShipped').toLowerCase()}</span>` : ''}${rc.n > s.on.length + rc.short.length ? `<span class="muted">· ${rc.n - s.on.length - rc.short.length} ${t('received').toLowerCase()}</span>` : ''}<button class="tb-btn btn-sm" data-received="${esc(v)}">${t('receivedAll', { n: s.on.length })}</button></div><div class="orows">${s.on.map(c => `<div class="orow" data-oid="${c.id}">${picHtml(c)}<span>${nameHtml(c)} <b class="q">×${rc.qtys[c.id] || ''}</b>${c.model ? ` <span class="chipm hide-m">${esc(c.model)}</span>` : ''}</span><span class="ra"><button class="ok" data-recvone="${c.id}">✓ ${t('received')}</button><button class="no" data-noship="${c.id}">${t('notShipped')}</button></span></div>`).join('')}</div></div>`;
  return h; }
function renderBoard(v) { const es = ES(); const vd = M.vendors[v]; if (!vd) return ''; const s = summary(v); const rc = L.receipts[v] && L.receipts[v].open.length ? L.receipts[v] : null; const lead = vendorLead(v); const late = rc && M.today > rc.expected;
  let h = `<div class="board"><div class="board-h"><h2>${esc(v)}</h2>`;
  if (v === 'Sticker Mule') { h += `<span class="when">${rc ? `${t('ordered')} <b>${fmtD(rc.day)}</b> · ${t('arrives')} <b>${fmtD(rc.expected)}</b>` : `${es ? 'Se pide cuando uno se acaba · siempre los tres juntos · plazo ~1 semana · último pedido' : 'Ordered when one runs out · always all three together · ~1-week lead · last order'} <b>${vd.lastOrder ? fmtMD(vd.lastOrder) : '—'}</b>`}</span>`;
    const all = [...s.q, ...s.due, ...s.next]; const rest = vendorCards(v).filter(c => !all.includes(c) && state(c) !== 'on-order');
    if (s.due.length + s.next.length + rest.length > 0) h += `<span class="right"><button class="tb-btn btn-amber" data-addids="${[...s.due, ...s.next, ...rest].map(c => c.id).join(',')}" data-addv="Sticker Mule">${t('addAllThree')}</button></span>`;
    h += `</div>` + receiptHtml(v, s);
    const dueAll = [...s.due, ...s.next];
    h += `<div class="lanes">${lane('q', 1, t('queued'), s.q.length, t('queuedSub'), s.q.map(c => icard(c, 'queued')).join('') + laneFoot(v), '', t('emptyQ'))}${lane('d', 2, t('due'), dueAll.length, dueAll.map(c => `${variantL(c).lead || shortName(c)} ${es ? 'el' : 'due'} ${fmtMD(c.expected)}`).join(' · '), dueAll.map(c => icard(c, 'due')).join(''), dueAll.length ? `<button class="tb-btn btn-amber btn-sm" data-addids="${dueAll.map(c => c.id).join(',')}" data-addv="Sticker Mule">${t('addAll')} ${dueAll.length}</button>` : '', s.on.length ? t('emptyDOnOrder', { n: s.on.length }) : t('emptyD', { d: fmtD(M.d2) }), dueAll.length ? '' : 'good')}${lane('n', 3, t('bundle'), rest.length, t('bundleSub'), rest.map(c => icard(c, 'bundle')).join(''), '', s.on.length ? (es ? 'Los tres ya están pedidos' : 'All three are on order') : (es ? 'Los tres ya están en la lista' : 'All three are already on the list'))}</div>`;
    h += copyLine(v) + `</div>`; return h; }
  const tom = M.d1 === addDays(M.today, 1);
  if (rc) h += `<span class="when">${t('ordered')} <b>${fmtD(rc.day)}</b> · ${late ? `<span style="color:var(--late);font-weight:600">${es ? 'se esperaba el' : 'was due'} ${fmtD(rc.expected)}</span>` : `${t('arrives')} <b>${fmtD(rc.expected)}</b>`} · ${t('nextOrder')} <b>${fmtD(M.d1)}</b></span>`;
  else h += `<span class="when">${t('goesOut')} <b>${tom ? t('tomorrow') + ' · ' : ''}${fmtD(M.d1)}</b><span class="hide-m"> · ${t('everyFriday')} · ${es ? `entrega en ${lead} ${lead === 1 ? 'día' : 'días'}` : `${lead}-day delivery`} · ${es ? 'último pedido' : 'last order'} <b>${vd.lastOrder ? fmtMD(vd.lastOrder) : '—'}</b></span></span>`;
  h += `</div>` + receiptHtml(v, s);
  const dueEmpty = s.on.length ? t('emptyDOnOrder', { n: s.on.length }) : t('emptyD', { d: fmtD(M.d2) });
  h += `<div class="lanes">${lane('q', 1, t('queued'), s.q.length, t('queuedSub'), s.q.map(c => icard(c, 'queued')).join('') + laneFoot(v), '', t('emptyQ'))}${lane('d', 2, t('due'), s.due.length, t('dueSub', { d: fmtD(M.d2) }), s.due.map(c => icard(c, 'due')).join(''), s.due.length ? `<button class="tb-btn btn-amber" data-addids="${s.due.map(c => c.id).join(',')}" data-addv="${esc(v)}">${t('addAll')} ${s.due.length}</button>` : '', dueEmpty, s.due.length ? '' : 'good')}${lane('c', 3, t('check'), s.chk.length, t('checkSub'), s.chk.map(c => icard(c, 'check')).join(''), v === 'Uline' ? `<button class="tb-btn btn-sm" data-sweep="1">${t('shelfList', { n: vendorCards('Uline').length })}</button>` : '', t('emptyC'))}</div>`;
  h += copyLine(v) + `</div>`; return h; }
function laneFoot(v) { const s = summary(v); if (!s.q.length) return ''; return `<div class="lane-foot"><p class="sum">${s.q.length} ${t('queued').toLowerCase()} · ${s.due.length} ${t('runningOut')}${s.est > 0 ? ` · ≈ ${money(s.est)}` : ''}</p><p class="sum muted">${ES() ? 'Los pedidos se hacen en el escritorio.' : 'Orders are placed at the desk.'}</p></div>`; }
function ulineRows(v) { return summary(v).q.map(c => ({ model: c.model, qty: c.inCart.qty, item: shortName(c) })); }
function copyText(v) { const q = summary(v).q; if (v === 'Uline') return ulinePasteText(ulineRows(v)).text; return q.map(c => `${shortName(c)} × ${c.inCart.qty}`).join('\n'); }
function copyLine(v) { const q = summary(v).q; if (!q.length) return '';
  const setup = `<details class="tech setup"><summary>${t('ulineSetup')}</summary><p class="muted" style="font-size:13px;max-width:80ch;margin:0 0 8px">${t('ulineSetupTxt')}</p><p style="margin:0;display:flex;gap:10px;flex-wrap:wrap;align-items:center"><a class="tb-btn btn-sm" href="${ULINE_HELPER_URL}" target="_blank" rel="noopener">${t('ulineHelper')}</a><a class="tb-btn btn-sm bookmarklet" href="${esc(ULINE_BOOKMARKLET)}" title="${ES() ? 'Arrástrame a la barra de marcadores' : 'Drag me to the bookmarks bar'}">${t('ulineBookmarklet')}</a></p></details>`;
  if (v === 'Uline') { const u = ulinePasteText(ulineRows(v)); return `<div class="copyline"><span class="eyebrow">${t('ulinePasteHead')}</span><pre class="paste">${esc(u.text) || '—'}</pre>${u.missing.length ? `<span class="missing">${t(u.missing.length === 1 ? 'noModel' : 'noModelN', { n: u.missing.length })}: ${u.missing.map(m => `<b>${esc(m.item)}</b> ×${m.qty}`).join(', ')}</span>` : ''}${setup}</div>`; }
  const link = cartLink(v); const miss = link && link.missing.length ? `<span class="missing">${t(link.missing.length === 1 ? 'noId' : 'noIdN', { n: link.missing.length })}: ${link.missing.map(m => `<b>${esc(m.item)}</b> ×${m.qty}`).join(', ')}</span>` : '';
  return `<div class="copyline"><span class="eyebrow">${esc(v)}</span><code>${esc(copyText(v)).replace(/\n/g, ' · ')}</code>${miss}${v === 'Amazon' ? setup : ''}</div>`; }
function cartLink(v) { const q = summary(v).q; const rows = q.map(c => ({ asin: c.asin, wmId: c.wmId, qty: c.inCart.qty, item: shortName(c) })); if (v === 'Amazon') return amazonQueueUrl(rows); if (v === 'Walmart') return walmartCartUrl(rows); return null; }
function copyToClipboard(txt) { return (navigator.clipboard && navigator.clipboard.writeText) ? navigator.clipboard.writeText(txt) : Promise.reject(new Error('no clipboard')); }
function selectPaste() { const code = $('.copyline pre, .copyline code'); if (!code) return; const rg = document.createRange(); rg.selectNodeContents(code); const sel = window.getSelection(); sel.removeAllRanges(); sel.addRange(rg); }
function renderActbar() { const es = ES(); const bar = $('#actbar'); if (S.view !== 'order' || !M.vendors[S.sel]) { bar.hidden = true; return; } const v = S.sel; const s = summary(v);
  let sum; if (v === 'Sticker Mule') sum = `<span><i style="background:var(--q)"></i><b>${s.q.length}</b> ${t('queued').toLowerCase()}</span><span><i style="background:var(--d)"></i><b>${s.due.length + s.next.length}</b> ${t('runningOut')}</span><span><i style="background:var(--ink-3)"></i><b>${vendorCards(v).filter(c => !['queued', 'due', 'due-next', 'on-order'].includes(state(c))).length}</b> ${t('toOrderTogether')}</span>`;
  else sum = `<span><i style="background:var(--q)"></i><b>${s.q.length}</b> ${t('queued').toLowerCase()}</span><span><i style="background:var(--d)"></i><b>${s.due.length}</b> ${t('runningOut')}</span><span><i style="background:var(--c)"></i><b>${s.chk.length}</b> ${t('toCheck')}</span><span>${s.est > 0 ? `${t('est')} <b>${money(s.est)}</b>` : ''}${s.unp ? ` · <b>${s.unp}</b> ${t('unpriced')}` : ''}</span>`;
  const rc = L.receipts[v] && L.receipts[v].open.length ? L.receipts[v] : null; let primary;
  if (s.q.length) primary = `<button class="tb-btn btn-primary btn-lg" data-mark="${esc(v)}">${rc ? t('addToOrder', { n: s.q.length, v }) : `${t('markOrdered', { n: s.q.length })} · ${esc(v)}`}</button>`;
  else if (rc || !s.due.length) { const nextV = [...DAY_VENDORS(), 'Sticker Mule'].filter(x => x !== v && M.vendors[x]).find(x => { const sx = summary(x); return sx.q.length + sx.due.length > 0; });
    if (nextV) { const sx = summary(nextV); primary = `<button class="tb-btn btn-lg" data-selv="${esc(nextV)}">${t('nextVendor', { v: nextV, n: sx.q.length + sx.due.length })}</button>`; }
    else { const placed = Object.values(L.receipts).filter(r => r.day === M.today).length; const tot = Object.values(L.receipts).filter(r => r.day === M.today).reduce((a, r) => a + r.est, 0); primary = `<button class="tb-btn btn-primary btn-lg" disabled>${placed ? `${t('allPlaced', { n: placed })}${tot > 0 ? ` · ≈ ${money(tot)}` : ''}` : `${t('nothingQueued')} · ${esc(v)}`}</button>`; } }
  else primary = `<button class="tb-btn btn-primary btn-lg" disabled>${t('nothingQueued')} · ${esc(v)} · ${s.due.length} ${t('runningOut')}</button>`;
  const uline = v === 'Uline' ? ulinePasteText(ulineRows(v)) : null; const link = cartLink(v);
  const vendorBtns = v === 'Uline' ? `<button class="tb-btn" data-ulinego="1" ${uline.lines ? '' : 'disabled'}>${t('ulineGo')}</button>`
    : `${link && link.url ? `<a class="tb-btn" data-cartgo="${esc(v)}" href="${esc(link.url)}" target="_blank" rel="noopener">${t(v === 'Amazon' ? 'amazonGo' : 'walmartGo')}</a>` : ''}<button class="tb-btn" data-openpages="${esc(v)}">${t('openPages', { n: s.q.length })}</button>`;
  bar.hidden = false; bar.innerHTML = `<div class="sum">${sum}</div><span class="grow"></span>${s.q.length ? `<button class="tb-btn" data-copy="${esc(copyText(v))}">${t('copy', { v })} (${uline ? uline.lines : s.q.length})</button>${vendorBtns}` : ''}${primary}`; wire(bar); }

// ---------- wiring (every handler is a data attribute) ----------
function wire(el) { const es = ES();
  $$('[data-qty]', el).forEach(inp => inp.onchange = () => setQty(+inp.dataset.qty, inp.value));
  $$('[data-inc]', el).forEach(b => b.onclick = () => setQty(+b.dataset.inc, byId(+b.dataset.inc).inCart.qty + 1));
  $$('[data-dec]', el).forEach(b => b.onclick = () => setQty(+b.dataset.dec, byId(+b.dataset.dec).inCart.qty - 1));
  $$('[data-setqty]', el).forEach(b => b.onclick = () => { const [id, q] = b.dataset.setqty.split(':').map(Number); setQty(id, q); });
  $$('[data-add]', el).forEach(b => b.onclick = () => addToCart(+b.dataset.add));
  $$('[data-addids]', el).forEach(b => b.onclick = () => addMany(b.dataset.addids.split(',').map(Number), b.dataset.addv));
  $$('[data-remove]', el).forEach(b => b.onclick = () => { const c = byId(+b.dataset.remove); const qty = c.inCart.qty; act(() => api.removeFromCart(c.id), `${t('remove')}: ${shortName(c)}`, () => act(() => api.addToCart({ cardId: c.id, qty, addedBy: 'desk' }))); });
  $$('[data-dismiss]', el).forEach(b => b.onclick = () => { const id = +b.dataset.dismiss; L.dismissed[id] = M.d2; saveL(); render(); toast(es ? `Hay — vuelve a aparecer en la revisión del ${fmtD(M.d2)}` : `Stocked — it comes back at the ${fmtD(M.d2)} check`, () => { delete L.dismissed[id]; saveL(); render(); }); });
  $$('[data-outclear]', el).forEach(b => b.onclick = () => { const cid = +b.dataset.outclear; L.outAck[cid] = true; saveL(); render(); toast(t('outClear'), () => { delete L.outAck[cid]; saveL(); render(); }); });
  $$('[data-mark]', el).forEach(b => b.onclick = () => markOrdered(b.dataset.mark, b));
  $$('[data-undo]', el).forEach(b => b.onclick = () => undoOrder(b.dataset.undo));
  $$('[data-received]', el).forEach(b => b.onclick = () => receiveOrder(b.dataset.received));
  $$('[data-copy]', el).forEach(b => b.onclick = () => { const txt = b.dataset.copy; copyToClipboard(txt).then(() => toast(t('copied') + ': ' + txt.replace(/\n/g, ' · ').slice(0, 60) + (txt.length > 60 ? '…' : '')), () => { selectPaste(); toast(es ? 'No se pudo copiar — el texto quedó seleccionado abajo, usa Ctrl+C' : 'Copy blocked — the list is selected below, press Ctrl+C'); }); });
  // One click: copy the paste-format list, then open Uline's Quick Order (its form carries an anti-forgery token, so it cannot be posted from here).
  $$('[data-ulinego]', el).forEach(b => b.onclick = () => { const txt = ulinePasteText(ulineRows('Uline')).text; const win = window.open(ulineQuickOrderUrl(txt), '_blank', 'noopener'); copyToClipboard(txt).then(() => toast(t('ulineHow')), () => { selectPaste(); toast(es ? 'Pega la lista de abajo en Uline (Ctrl+C aquí)' : 'Paste the list below into Uline (Ctrl+C here)'); }); if (!win) toast(es ? 'El navegador bloqueó la pestaña — abre uline.com/QuickOrder' : 'The browser blocked the tab — open uline.com/QuickOrder'); });
  $$('.bookmarklet', el).forEach(a => a.onclick = e => { e.preventDefault(); toast(es ? 'Arrástralo a la barra de marcadores; tócalo en la página de Uline' : 'Drag it to the bookmarks bar; click it on the Uline page'); });
  $$('[data-cartgo]', el).forEach(a => a.onclick = () => { toast(t(a.dataset.cartgo === 'Amazon' ? 'amazonHow' : 'walmartHow')); });
  $$('[data-openpages]', el).forEach(b => b.onclick = () => { const q = summary(b.dataset.openpages).q.filter(c => c.url); q.forEach(c => window.open(c.url, '_blank', 'noopener')); toast(`${es ? 'Abriendo' : 'Opening'} ${q.length} ${es ? 'páginas' : 'pages'}`); });
  $$('[data-sweep]', el).forEach(b => b.onclick = () => openSweep());
  $$('[data-selv]', el).forEach(b => b.onclick = () => { S.sel = b.dataset.selv; render(); window.scrollTo(0, 0); });
  $$('[data-recvone]', el).forEach(b => b.onclick = () => receiveItem(+b.dataset.recvone));
  $$('[data-noship]', el).forEach(b => b.onclick = () => notShipped(+b.dataset.noship));
  $$('[data-nudge]', el).forEach(b => b.onclick = () => { const id = +b.dataset.nudge; if (L.nudged[id] === M.today) return; act(async () => { const r = await api.addToCart({ cardId: id, qty: 1, addedBy: 'desk' }); if (r.mode !== 'reorder_request') throw new Error('not a Grove card'); L.nudged[id] = M.today; saveL(); }, es ? 'Aviso reenviado a Damon · máximo 1 por día por tarjeta' : 'Asked Damon again · at most 1 per day per card'); });
  $$('[data-markg]', el).forEach(b => b.onclick = () => { const id = +b.dataset.markg; L.groveOrdered[id] = { at: M.today, expected: addDays(M.today, 75) }; saveL(); render(); toast(`${es ? 'Pedido con Damon' : 'Ordered with Damon'} — ${shortName(byId(id))} · ${es ? 'llega ~' : 'arrives ~'}${fmtMD(addDays(M.today, 75))}`, () => { delete L.groveOrdered[id]; saveL(); render(); }); });
  $$('[data-recv]', el).forEach(b => b.onclick = () => openReceive(+b.dataset.recv));
  $$('[data-printv]', el).forEach(b => b.onclick = () => printGroup(b.dataset.printv));
  $$('[data-fmt]', el).forEach(b => b.onclick = () => { S.printFmt = b.dataset.fmt; render(); });
  $$('[data-p]', el).forEach(li => li.onclick = () => { S.printSel = +li.dataset.p; render(); }); }
function setQty(id, v) { const c = byId(id); if (!c || !c.inCart) return; const n = parseInt(v, 10); v = Number.isFinite(n) ? Math.max(1, n) : c.suggested; if (v === c.inCart.qty) { render(); return; } act(() => api.setCartQty(id, v)); }
function addToCart(id) { const c = byId(id); act(() => api.addToCart({ cardId: id, qty: c.suggested, addedBy: 'desk' }), `${t('add')} ${c.suggested} ${unitOf(c, c.suggested)} · ${shortName(c)} → ${c.vendor}`, () => act(() => api.removeFromCart(id))); }
function addMany(ids, v) { act(async () => { for (const id of ids) { const c = byId(id); if (c && !c.inCart) await api.addToCart({ cardId: id, qty: c.suggested, addedBy: 'desk' }); } }, `${ES() ? 'Agregados' : 'Added'} ${ids.length} → ${v}`, () => act(async () => { for (const id of ids) await api.removeFromCart(id).catch(() => {}); })); }
async function markOrdered(v, btn) { const es = ES(); const q = summary(v).q; if (!q.length) return; if (btn) btn.classList.add('busy');
  let est = 0; q.forEach(c => { const e = lineEst(c, c.inCart.qty); if (e != null) est += e; }); const qtys = {}; q.forEach(c => qtys[c.id] = c.inCart.qty);
  const eta = q.reduce((m, c) => { const d = addDays(M.today, leadOf(c)); return d > m ? d : m; }, addDays(M.today, 1));
  await act(async () => { const r = await api.markOrdered(v, 'desk'); const ex = L.receipts[v] && L.receipts[v].open.length ? L.receipts[v] : null;
    if (ex) { ex.n += q.length; ex.est += est; Object.assign(ex.qtys, qtys); ex.open.push(...q.map(c => c.id)); ex.restore.push(...q.map(c => [c.id, qtys[c.id]])); ex.orderIds.push(r.orderId); ex.whenISO = nowISO(); ex.undoUntil = Date.now() + 10 * 60e3; if (eta > ex.expected) ex.expected = eta; }
    else L.receipts[v] = { orderIds: [r.orderId], day: M.today, n: q.length, est, whenISO: nowISO(), expected: eta, undoUntil: Date.now() + 10 * 60e3, qtys, open: q.map(c => c.id), short: [], restore: q.map(c => [c.id, qtys[c.id]]) };
    saveL(); }, `${es ? 'Marcado como pedido' : 'Marked ordered'} — ${v} · ${q.length} ${t('items')}`); }
function undoOrder(v) { const r = L.receipts[v]; if (!r) return; act(async () => { for (const [id, qty] of r.restore) await api.addToCart({ cardId: id, qty, addedBy: 'desk' }); r.orderIds.forEach(id => L.undone[id] = true); r.open.forEach(id => { delete L.backorder[id]; }); delete L.receipts[v]; saveL(); }, ES() ? 'Pedido deshecho — las tarjetas volvieron' : 'Order undone — the cards are back'); }
function closeReceipt(v) { const r = L.receipts[v]; if (r && !r.open.length) { r.receivedAt = M.today; r.closed = true; } }
function receiveOrder(v) { const r = L.receipts[v]; if (!r) return; r.open.forEach(id => { L.received[id] = M.today; }); r.open = []; closeReceipt(v); saveL(); render(); toast(`${t('received')} — ${v}`); }
function receiveItem(id) { const v = orderedMap(L.receipts)[id]; if (!v) return; const r = L.receipts[v]; r.open = r.open.filter(x => x !== id); L.received[id] = M.today; closeReceipt(v); saveL(); render(); toast(`${t('received')} — ${shortName(byId(id))}${!r.open.length ? ` · ${ES() ? 'pedido completo' : 'order complete'} · ${v}` : ''}`); }
function notShipped(id) { const v = orderedMap(L.receipts)[id]; if (!v) return; const r = L.receipts[v]; r.open = r.open.filter(x => x !== id); r.short.push(id); L.backorder[id] = { at: M.today, vendor: v }; closeReceipt(v); saveL(); render();
  toast(`${t('notShipped')} — ${shortName(byId(id))} · ${ES() ? 'vuelve a «Por acabarse» para la próxima revisión' : 'back in “About to run out” for the next check'}`, () => { delete L.backorder[id]; r.short = r.short.filter(x => x !== id); r.open.push(id); r.closed = false; saveL(); render(); }); }
setInterval(() => { $$('[data-undo]').forEach(b => { const r = L && L.receipts[b.dataset.undo]; if (!r) return; const s = Math.max(0, ((r.undoUntil - Date.now()) / 1e3) | 0); b.textContent = `${t('undo')} · ${(s / 60) | 0}:${String(s % 60).padStart(2, '0')}`; if (s === 0) b.disabled = true; }); }, 1000);

// ---------- history ----------
function renderHistory() { const es = ES(); const months = Object.keys(M.spend).sort(); const lastMon = months[months.length - 1]; const sp = M.spend[lastMon] || {}; const spendRows = Object.entries(sp).sort((a, b) => b[1] - a[1]); const totMon = spendRows.reduce((a, [, v]) => a + v, 0);
  const rows = M.orders.slice(0, 12);
  const rcByOrder = {}; for (const [v, r] of Object.entries(L.receipts)) for (const oid of r.orderIds || []) rcByOrder[oid] = { v, r };
  let h = `<section class="sec"><div class="sec-head"><h2>${t('history')}</h2><span class="sec-meta">${M.orders.length} ${es ? 'pedidos desde' : 'orders since'} ${M.orders.length ? fmtMD(localDay(M.orders[M.orders.length - 1].orderedAt)) : '—'}</span></div><div class="hist"><div class="list-card" style="overflow-x:auto"><table class="grid"><thead><tr><th>${es ? 'Fecha' : 'Date'}</th><th>${es ? 'Proveedor' : 'Vendor'}</th><th>${t('items')}</th><th>${es ? 'Contenido' : 'What'}</th><th>${es ? 'Estado' : 'Status'}</th></tr></thead><tbody>`;
  rows.forEach(o => { const rc = rcByOrder[o.id]; const undone = L.undone[o.id]; let status;
    if (undone) status = `<span class="muted">${t('undo')}</span>`;
    else if (rc && rc.r.open.length) status = `<button class="tb-btn btn-sm" data-received="${esc(rc.v)}">${t('received')}</button>`;
    else if (rc) { const lateD = rc.r.receivedAt && rc.r.receivedAt > rc.r.expected ? daysBetween(rc.r.expected, rc.r.receivedAt) : 0; status = `<span class="muted">${t('received')} ${fmtMD(rc.r.receivedAt || rc.r.expected)}${lateD > 0 ? ` · ${lateD} d ${t('lateShort')}` : ''}${rc.r.short.length ? ` · ${rc.r.short.length} ${t('notShipped').toLowerCase()}` : ''}</span>`; }
    else status = `<span class="muted">${o.placedBy ? esc(o.placedBy) : (es ? 'página anterior' : 'old page')}</span>`;
    h += `<tr class="${rc ? 'new' : ''} ${undone ? 'strike' : ''}"><td class="mono">${fmtD(localDay(o.orderedAt))}</td><td><b>${esc(o.vendor)}</b></td><td class="mono">${o.items.length}</td><td class="muted" style="font-size:13px">${o.items.slice(0, 3).map(i => `${esc((byId(i.cardId) ? shortName(byId(i.cardId)) : i.item).slice(0, 24))} ×${i.qty}`).join(' · ')}${o.items.length > 3 ? ' …' : ''}</td><td>${status}</td></tr>`; });
  h += `</tbody></table></div><div class="tiles">`;
  h += `<div class="tile"><div class="label">${es ? `Gasto ${lastMon || ''} (estimado)` : `${lastMon || ''} spend (estimate)`}</div><div class="value">${money(totMon)}</div><div class="sub">${spendRows.map(([v, n]) => `${esc(v)} ${money(n)}`).join(' · ') || '—'}</div></div>`;
  h += `<div class="tile"><div class="label">${es ? 'Pedidos a 3 días de otro, mismo proveedor' : 'Orders within 3 days of another, same vendor'}</div><div class="value">${M.fragmentation.length}</div><div class="sub">${M.fragmentation.slice(-4).map(f => `${f[0]} ${fmtMD(f[1])}→${fmtMD(f[2])}`).join(' · ') || '—'}</div></div>`;
  const q3 = months.slice(-3).reduce((a, m) => a + Object.values(M.spend[m] || {}).reduce((x, y) => x + y, 0), 0);
  h += `<div class="tile"><div class="label">${es ? 'Últimos 3 meses (estimado)' : 'Last 3 months (estimate)'}</div><div class="value">${money(q3)}</div><div class="sub">${es ? 'precio por pieza × cantidades pedidas' : 'per-piece price × ordered quantities'}</div></div>`;
  h += `<div class="tile"><div class="label">${es ? 'Tarjetas con nivel de pedido' : 'Cards with a reorder level'}</div><div class="value">${cards().filter(c => c.numericLevels).length}<small>/ ${cards().length}</small></div><div class="sub">${cards().filter(c => !c.numericLevels).length} ${es ? 'sin nivel todavía' : 'with no level set yet'}</div></div>`;
  h += `</div></div></section>`; return h; }

// ---------- SWEEP ----------
function openSweep() { const es = ES(); const all = vendorCards('Uline').sort(bySlot); const flagged = all.filter(c => state(c) === 'check'); const rest = all.filter(c => !flagged.includes(c));
  $('#swTitle').textContent = t('sweepTitle', { n: all.length, f: flagged.length });
  const row = c => { const st = state(c); const est = lineEst(c, c.suggested); return `<div class="swrow">${picHtml(c)}<div><b>${nameHtml(c)}</b> ${slotChip(c)}<div class="r">${c.numericLevels ? `${t('reorderAt')} ${c.reorder | 0} · ${t('fillTo')} ${c.fill | 0}` : `<span style="color:var(--d-text)">${es ? 'sin nivel — la tarjeta dice' : 'no level — card says'} ${esc(c.orderQtyRaw)}</span>`} · ${st === 'queued' ? `<b style="color:var(--q)">${t('queued').toLowerCase()} ${c.inCart.qty}</b>` : (st === 'on-order' ? `<b>${t('onOrder')}</b>` : evidence(c))}</div></div>${['queued', 'on-order'].includes(st) ? '<span></span>' : `<span><button class="tb-btn btn-sm" data-add="${c.id}">${t('add')} ${c.suggested}</button>${est && est > 200 ? `<span class="tot">${money(est)}</span>` : ''}</span>`}</div>`; };
  let h = `<p class="muted" style="margin:0 0 6px;font-size:14px">${es ? 'Recorre el estante en este orden y agrega lo que esté por debajo de su nivel.' : 'Walk the shelf in this order and add anything below its level.'}</p>`;
  if (flagged.length) h += `<div class="eyebrow" style="margin-top:8px"><i style="display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--c);margin-right:6px"></i>${es ? 'MARCADAS' : 'FLAGGED'} · ${flagged.length}</div>` + flagged.map(row).join('');
  h += `<div class="eyebrow" style="margin-top:12px">${es ? 'RESTO DEL ESTANTE' : 'REST OF THE SHELF'} · ${rest.length}</div>`; let zone = null; rest.forEach(c => { if (c.zone !== zone) { zone = c.zone; h += `<div class="eyebrow" style="margin-top:10px;color:var(--ink-2)">${esc(zone)}</div>`; } h += row(c); });
  $('#swBody').innerHTML = h; wire($('#swBody')); $$('[data-add]', $('#swBody')).forEach(b => { const f = b.onclick; b.onclick = async () => { await f(); openSweep(); }; }); $('#swPrint').onclick = () => window.print(); const d = $('#sweep'); if (!d.open) d.showModal(); }

// ---------- RECEIVE BINS ----------
function openReceive(id) { const es = ES(); const c = byId(id); $('#rvTitle').textContent = `${t('receiveBins')} · ${shortName(c)}`;
  $('#rvBody').innerHTML = `<div class="f"><label>${es ? '¿Cuántas bolsas llegaron?' : 'How many bags arrived?'}</label><input id="rvBags" type="number" min="1" value="2500" style="font-size:22px;height:52px"></div><div class="f2"><div class="f"><label>${es ? 'Bolsas por bin' : 'Bags per bin'}</label><input id="rvPer" type="number" min="50" value="200"></div><div class="f"><label>${es ? 'Lote / referencia Grove' : 'Lot / Grove reference'}</label><input id="rvLot" value="GRV-${c.id}-${M.today.slice(5).replace('-', '')}"></div></div><div class="live" id="rvLive"></div>`;
  const live = () => { const bags = +$('#rvBags').value || 0, per = +$('#rvPer').value || 200; const bins = Math.ceil(bags / per); $('#rvLive').innerHTML = es ? `= <b>${bins}</b> bins de ${per}${bags % per ? ` (el último con ${bags % per})` : ''} · se imprimen <b>${bins}</b> tarjetas de hoja completa, una por bin` : `= <b>${bins}</b> bins of ${per}${bags % per ? ` (last one holds ${bags % per})` : ''} · prints <b>${bins}</b> full-sheet cards, one per bin`; $('#rvSave').textContent = es ? `Recibir e imprimir ${bins} tarjetas` : `Receive and print ${bins} bin cards`; };
  $('#rvBags').oninput = live; $('#rvPer').oninput = live; live();
  $('#rvSave').onclick = () => { const bags = +$('#rvBags').value || 0, per = +$('#rvPer').value || 200; const bins = Math.ceil(bags / per); L.bins[id] = { total: bins, sealed: bins, perBin: per, at: M.today, lot: $('#rvLot').value.trim() }; delete L.groveOrdered[id]; saveL(); $('#recv').close(); render(); toast(es ? `Recibidos ${bins} bins · imprime las ${bins} tarjetas desde Imprimir` : `Received ${bins} bins · print the ${bins} bin cards from Print`); };
  const d = $('#recv'); if (!d.open) d.showModal(); }

// ---------- CARDS ----------
const STATE_ORDER = { queued: 0, 'on-order': 1, requested: 2, due: 3, 'due-next': 4, check: 5, ok: 6, 'no-history': 7 };
function stateLabel(st) { return { queued: t('queued'), 'on-order': t('onOrder'), requested: t('requested'), due: t('dueS'), 'due-next': t('nextWeek'), check: t('check'), ok: t('ok'), 'no-history': t('noHistory') }[st] || st; }
function renderCards() { const es = ES(); const el = $('#view-cards'); const om = outMap();
  const cnt = {}; cards().forEach(c => { const s = state(c); cnt[s] = (cnt[s] || 0) + 1; });
  const chips = [['all', t('all'), cards().length, ''], ['queued', t('queued'), cnt.queued || 0, 'var(--q)'], ['due', t('dueS'), cnt.due || 0, 'var(--d)'], ['due-next', t('nextWeek'), cnt['due-next'] || 0, 'var(--d)'], ['check', t('check'), cnt.check || 0, 'var(--c)'], ['on-order', t('onOrder'), cnt['on-order'] || 0, 'var(--ink-3)'], ['requested', t('requested'), cnt.requested || 0, 'var(--r)'], ['ok', t('ok'), cnt.ok || 0, ''], ['no-history', t('noHistory'), cnt['no-history'] || 0, '']];
  const vendors = [...new Set(cards().map(c => c.vendor))].sort(), zones = [...new Set(cards().map(c => c.zone))].sort();
  const noLevel = cards().filter(c => !c.numericLevels).length, noSlot = cards().filter(c => c.zone === 'Unassigned').length;
  let h = `<div class="strip">${S.q ? `<button class="chip qpill" id="qpill" aria-label="${es ? 'Quitar búsqueda' : 'Clear search'}">“<b>${esc(S.q)}</b>” <span class="x">×</span></button>` : ''}${chips.map(([k, l, n, col]) => `<button class="chip" aria-pressed="${S.filter === k}" data-f="${k}">${col ? `<i style="background:${col}"></i>` : ''}${l}<span class="n">${n}</span></button>`).join('')}<span class="right"><select id="fv" aria-label="${es ? 'Proveedor' : 'Vendor'}"><option value="">${es ? 'Todos los proveedores' : 'All vendors'}</option>${vendors.map(v => `<option ${S.vendor === v ? 'selected' : ''}>${esc(v)}</option>`).join('')}</select><select id="fz" aria-label="${es ? 'Zona' : 'Zone'}"><option value="">${es ? 'Todas las zonas' : 'All zones'}</option>${zones.map(v => `<option ${S.zone === v ? 'selected' : ''}>${esc(v)}</option>`).join('')}</select></span></div>`;
  h += `<div class="strip" style="margin-top:-4px"><span class="chip gapc">${noLevel} ${es ? 'sin nivel de pedido' : 'with no reorder level'}</span><span class="chip gapc">${noSlot} ${es ? 'sin lugar en el estante' : 'with no shelf spot'}</span><span class="muted" style="font-size:13px">${es ? 'Toca una tarjeta para fijar sus niveles.' : 'Tap a card to set its levels.'}</span></div>`;
  const list = cards().filter(c => (S.filter === 'all' || state(c) === S.filter) && (!S.vendor || c.vendor === S.vendor) && (!S.zone || c.zone === S.zone) && (!S.q || (c.item + ' ' + (c.model || '') + ' ' + c.vendor + ' ' + c.zone).toLowerCase().includes(S.q)));
  list.sort((a, b) => (STATE_ORDER[state(a)] - STATE_ORDER[state(b)]) || ((a.expected || '9').localeCompare(b.expected || '9')) || a.item.localeCompare(b.item));
  const msub = c => { const st = state(c); const v = orderedMap(L.receipts)[c.id]; const rc = v && L.receipts[v]; const extra = st === 'queued' ? `×${c.inCart.qty}` : (st === 'on-order' && rc ? `${t('arrives')} ${fmtMD(rc.expected)}` : (st === 'due' && c.expected ? `${t('expected', { d: fmtMD(c.expected) })}` : '')); return [c.zone === 'Unassigned' ? (es ? 'sin lugar' : 'no spot') : slotTxt(c), c.vendor, extra].filter(Boolean).join(' · '); };
  h += `<div class="pgrid">` + list.map(c => { const st = state(c); const out = !!om[c.id]; const showBadge = out || !['ok', 'no-history'].includes(st); return `<button class="pc" data-id="${c.id}" aria-label="${esc(c.item)}">${picHtml(c)}${showBadge ? `<span class="badges"><span class="badge s-${out ? 'out' : st}">${out ? t('redCard') : stateLabel(st)}</span>${st === 'queued' ? `<span class="badge qty">×${c.inCart.qty} ${unitOf(c, c.inCart.qty)}</span>` : ''}</span>` : ''}<div class="body"><h4 class="nm">${nameHtml(c)}</h4><div class="msub">${esc(msub(c))}</div><div class="chips">${slotChip(c)}</div><div class="lv">${c.numericLevels ? `${t('reorderAt')} <b>${c.reorder | 0}</b> → ${t('fillTo')} <b>${c.fill | 0}</b>` : `<span class="chipm gap">${es ? 'Sin nivel de pedido' : 'No reorder level'}</span>`}</div><div class="why">${evidence(c)}</div><div class="foot"><span class="vend">${esc(c.vendor)}</span><span class="tb-btn btn-sm">${c.numericLevels ? t('edit') : t('setLevels')}</span></div></div></button>`; }).join('') + `</div>`;
  if (!list.length) h += `<div class="empty" style="margin-top:12px">${es ? 'Ninguna tarjeta coincide.' : 'No cards match.'} <button class="tb-btn btn-sm" id="clearFilters">${es ? 'Limpiar filtros' : 'Clear filters'}</button></div>`;
  el.innerHTML = h;
  const cf = $('#clearFilters', el); if (cf) cf.onclick = () => { S.filter = 'all'; S.vendor = ''; S.zone = ''; S.q = ''; $('#q').value = ''; render(); };
  const qp = $('#qpill', el); if (qp) qp.onclick = () => { S.q = ''; $('#q').value = ''; render(); };
  $$('[data-f]', el).forEach(b => b.onclick = () => { S.filter = b.dataset.f; render(); });
  $('#fv', el).onchange = e => { S.vendor = e.target.value; render(); }; $('#fz', el).onchange = e => { S.zone = e.target.value; render(); };
  $$('.pc[data-id]', el).forEach(r => r.onclick = () => openEditor(+r.dataset.id)); }

// ---------- EDITOR ----------
export function openEditor(id) { const es = ES(); const c = id ? byId(id) : { item: '', vendor: 'Amazon', zone: 'Supply rack', slot: '', fill: 1, reorder: null, numericLevels: false, url: '', qtyHist: [], orderDays: [], n: 0, leadDays: 1 };
  $('#edTitle').textContent = id ? shortName(c) : (es ? 'Nueva tarjeta' : 'New card');
  const zones = [...new Set([...ZONES, ...cards().map(x => x.zone)])]; const vendors = [...new Set(['Uline', 'Amazon', 'Walmart', 'Sticker Mule', 'Grove', ...cards().map(x => x.vendor)])].filter(v => v !== '(Unspecified)');
  const units = [['each', es ? 'c/u' : 'each'], ['pack', es ? 'paquete' : 'pack'], ['case', es ? 'caja grande' : 'case'], ['box', es ? 'caja' : 'box'], ['roll', es ? 'rollo' : 'roll']]; const pref = L.prefs[id] || {}; const curFmt = pref.printFmt || (c.vendor === 'Grove' ? 'sheet' : 'card');
  let h = `<div class="dlg-pic">${id ? picHtml(c) : '<div class="pic"></div>'}<div class="stack"><div class="f"><label>${es ? 'Artículo' : 'Item'}</label><input id="edItem" value="${esc(c.item)}" placeholder="${es ? 'Nombre del artículo' : 'Item name'}"></div><div class="f3"><div class="f"><label>${es ? 'Proveedor' : 'Vendor'}</label><select id="edVendor">${vendors.map(v => `<option ${v === c.vendor ? 'selected' : ''}>${esc(v)}</option>`).join('')}</select></div><div class="f"><label>${es ? 'Zona' : 'Zone'}</label><select id="edZone">${zones.map(v => `<option ${v === c.zone ? 'selected' : ''}>${esc(v)}</option>`).join('')}</select></div><div class="f"><label>${es ? 'Posición' : 'Slot'}</label><input id="edSlot" value="${esc(c.slot || '')}" placeholder="A-2"></div></div></div></div>
  <div class="group"><h4>${es ? 'Niveles · dos bins' : 'Levels · two bins'}</h4><div class="f3"><div class="f"><label>${t('fillTo')} · ${t('bothBins')}</label><input id="edFill" type="number" min="0" value="${c.fill != null ? c.fill | 0 : ''}"></div><div class="f"><label>${t('reorderAt')} · ${t('backBin')}</label><input id="edRe" type="number" min="0" value="${c.numericLevels && c.reorder != null ? c.reorder | 0 : ''}" placeholder="—"></div><div class="f"><label>${es ? 'Unidad' : 'Unit'}</label><select id="edUnit"><option value="">${es ? 'auto' : 'auto'}</option>${units.map(([k, l]) => `<option value="${k}" ${(pref.unit || '') === k ? 'selected' : ''}>${l}</option>`).join('')}</select></div></div>
  <label style="display:flex;gap:8px;align-items:center;font-size:14px"><input type="checkbox" id="edSignal" ${c.numericLevels ? '' : 'checked'}> ${es ? 'Solo señal — pedir a ojo cuando la tarjeta aparece' : 'Signal only — ordered by eye when the card shows'}</label>
  <div class="live" id="edLive"></div></div>`;
  if (id && L.outLog[id]) h += `<div class="prop" style="border-left-color:var(--late)"><div><b style="color:var(--late)">${es ? `Tarjeta roja ${L.outLog[id]}× — se acabó por completo` : `Red card fired ${L.outLog[id]}× — completely out`}</b><div class="muted" style="margin-top:4px">${es ? 'Koa: nunca debería pasar. Sube Llenar a / Pedir a para que el bin de atrás cubra el plazo.' : 'Koa’s rule: this should never happen. Raise Fill to / Reorder at so the back bin covers the lead time.'}</div></div></div>`;
  if (id) h += `<div class="group"><h4>${es ? 'Últimas 16 semanas' : 'Last 16 weeks'}</h4>${timeline(c)}<div class="muted" style="font-size:13px">${c.n ? `${c.n} ${es ? 'días de pedido' : 'order days'} · ${es ? 'mediana' : 'median gap'} ${c.medianGap ? Math.round(c.medianGap) + ' d' : '—'}${c.levelsChanged ? ` · ${es ? 'niveles cambiados' : 'levels changed'} ${fmtMD(c.levelsChanged)}` : ''}${c.expected ? ` · ${es ? 'esperado' : 'expected'} ${fmtMD(c.expected)}` : ''}` : (es ? 'sin pedidos registrados' : 'no orders logged')}</div></div>`;
  h += `<div class="f2"><div class="f"><label>${es ? 'URL del producto' : 'Product URL'}</label><input id="edUrl" value="${esc(c.url || '')}"></div><div class="f"><label>${es ? 'Formato de impresión' : 'Print format'}</label><div class="fmt" style="padding-top:6px">${[['card', 'fmtCard'], ['sheet', 'fmtSheet']].map(([k, l]) => `<button type="button" class="chip" data-fmt="${k}" aria-pressed="${curFmt === k}">${t(l)}</button>`).join('')}</div></div></div>
  <div class="f2"><div class="f"><label>${es ? 'Entrega (texto de la tarjeta)' : 'Delivery (card text)'}</label><input id="edDelivery" value="${esc(c.deliveryRaw || '')}" placeholder="1 Day"></div><div class="f"><label>${es ? 'Precio (texto de la tarjeta)' : 'Price (card text)'}</label><input id="edPrice" value="${esc(c.priceRaw || '')}" placeholder="$1.00/Pc"></div></div>`;
  if (id) h += `<div class="danger"><span>${es ? 'Ocultar en este escritorio (se puede volver a mostrar) · o borrar de la base de datos para siempre.' : 'Hide from this desk (can be shown again) · or delete from the database for good.'}</span><span style="display:flex;gap:6px"><button type="button" class="tb-btn btn-sm" data-archive="1">${t('hideCard')}</button><button type="button" class="tb-btn btn-sm" data-delete="1">${t('deleteForever')}</button></span></div>`;
  $('#edBody').innerHTML = h; $('#edBody').dataset.id = id || '';
  ['edFill', 'edRe', 'edSignal'].forEach(i => $('#' + i).oninput = liveLine); liveLine();
  $$('.fmt .chip').forEach(b => b.onclick = () => { $$('.fmt .chip').forEach(x => x.setAttribute('aria-pressed', 'false')); b.setAttribute('aria-pressed', 'true'); });
  const ab = $('[data-archive]'); if (ab) ab.onclick = () => archiveCard(id);
  const db = $('[data-delete]'); if (db) db.onclick = () => { if (!confirm(es ? `¿Borrar «${c.item}» para siempre? Las tarjetas impresas dejarán de funcionar.` : `Delete “${c.item}” for good? Printed cards for it will stop working.`)) return; $('#editor').close(); act(() => api.deleteCard(id), `${es ? 'Borrada' : 'Deleted'} — ${shortName(c)}`); };
  $('#editor').showModal(); }
function archiveCard(id) { const c = byId(id); if (!L.archived.includes(id)) L.archived.push(id); saveL(); $('#editor').close(); act(async () => {}, `${t('archived')} — ${shortName(c)}`, () => { L.archived = L.archived.filter(x => x !== id); saveL(); act(async () => {}, `${t('restored')} — ${shortName(c)}`); }); }
function liveLine() { const es = ES(); const fill = +$('#edFill').value || 0, re = $('#edRe').value === '' ? null : +$('#edRe').value, sig = $('#edSignal').checked; const id = +$('#edBody').dataset.id; const c = id ? byId(id) : null;
  let txt; if (sig || re == null) txt = es ? `Cada escaneo pide <b>${fill || 1}</b> (lo que dice la tarjeta). Sin Pedir a, la hoja no puede sugerir ni prever.` : `Each scan orders <b>${fill || 1}</b> (what the card says). Without a Reorder at, the sheet cannot suggest or forecast.`;
  else { const n = fill > re ? fill - re : fill; txt = es ? `El bin de adelante se repone con <b>${n}</b> (${fill} − ${re}); el bin de atrás guarda <b>${re}</b> y debe cubrir el plazo${c && c.medianGap ? ` · cubre ~<b>${(c.medianGap / 7).toFixed(1)} sem</b> al ritmo actual (~${Math.round(c.medianGap)} d entre pedidos)` : ''}.` : `Front bin refills with <b>${n}</b> (fill ${fill} − reorder ${re}); the back bin holds <b>${re}</b> and must cover the lead time${c && c.medianGap ? ` · covers ~<b>${(c.medianGap / 7).toFixed(1)} wk</b> at the current ~${Math.round(c.medianGap)}-day gap` : ''}.`; }
  $('#edLive').innerHTML = txt; }
export function saveCard() { const es = ES(); const id = +$('#edBody').dataset.id; const c = id ? byId(id) : null; const isNew = !c;
  const item = $('#edItem').value.trim(); if (!item) { toast(es ? 'Ponle nombre al artículo' : 'Give the item a name'); return; }
  const fill = +$('#edFill').value || (c && c.fill) || 1, re = $('#edRe').value === '' ? null : +$('#edRe').value, sig = $('#edSignal').checked;
  const fmtBtn = $('.fmt .chip[aria-pressed="true"]'); const unit = $('#edUnit').value;
  const next = { id, item, vendor: $('#edVendor').value, zone: $('#edZone').value, slot: $('#edSlot').value.trim(), url: $('#edUrl').value.trim(), fill, reorder: sig ? null : re, numericLevels: !sig && re != null, deliveryRaw: $('#edDelivery').value.trim(), priceRaw: $('#edPrice').value.trim(), picture: c ? c.picture : '', imageFile: c ? c.imageFile : '' };
  const levelsChanged = c && (c.fill !== next.fill || c.reorder !== next.reorder || c.numericLevels !== next.numericLevels);
  const raw = toRawCard(next, RAW[id] || {});
  $('#editor').close();
  act(async () => { if (isNew) { delete raw.id; await api.addCard(raw); } else await api.updateCard(raw); const pid = id || null; if (pid) { L.prefs[pid] = { unit: unit || undefined, printFmt: fmtBtn ? fmtBtn.dataset.fmt : undefined }; if (levelsChanged) L.levelsChanged[pid] = M.today; delete L.printed[pid]; saveL(); } }, isNew ? (es ? 'Tarjeta creada · imprímela desde Imprimir' : 'Card created · print it from Print') : (es ? 'Cambios guardados' : 'Saved')); }
function timeline(c) { const W = 560, H = 78, Lm = 8, R = 8; const TODAY = pd(M.today); const start = new Date(TODAY); start.setDate(start.getDate() - 112); const x = d => Lm + ((pd(d) - start) / (TODAY - start)) * (W - Lm - R);
  let s = `<svg class="tl" viewBox="0 0 ${W} ${H}" role="img" aria-label="Order timeline">`;
  if (c.expected) { const xe = x(c.expected); s += `<rect class="win" x="${Math.max(Lm, xe - 10)}" y="18" width="20" height="22"/>`; }
  s += `<line class="ax" x1="${Lm}" x2="${W - R}" y1="40" y2="40"/>`;
  [-16, -12, -8, -4, 0].forEach(w => { const d = new Date(TODAY); d.setDate(d.getDate() + w * 7); const xx = Lm + ((d - start) / (TODAY - start)) * (W - Lm - R); s += `<line class="ax" x1="${xx}" x2="${xx}" y1="40" y2="44"/><text x="${xx}" y="60" text-anchor="${w === 0 ? 'end' : 'middle'}">${w === 0 ? (ES() ? 'hoy' : 'today') : MON[d.getMonth()] + ' ' + d.getDate()}</text>`; });
  if (c.levelsChanged && pd(c.levelsChanged) > start) { const xl = x(c.levelsChanged); s += `<line class="lc" x1="${xl}" x2="${xl}" y1="12" y2="40"/><text x="${xl + 3}" y="12">${ES() ? 'niveles' : 'levels'}</text>`; }
  const hist = Object.fromEntries((c.qtyHist || []).map(([d, q]) => [d, q]));
  (c.orderDays || []).forEach(d => { if (pd(d) < start) return; const xx = x(d); s += `<circle class="dot" cx="${xx}" cy="40" r="5"/>`; if (hist[d]) s += `<text x="${xx}" y="30" text-anchor="middle">${hist[d]}</text>`; });
  return s + `</svg>`; }

// ---------- PRINT ----------
function qrSvg(text) { try { if (typeof window.qrcode === 'function') { const q = window.qrcode(0, 'M'); q.addData(text); q.make(); return q.createSvgTag({ cellSize: 4, margin: 0, scalable: true }); } } catch (e) { console.warn('qr', e); } return `<svg viewBox="0 0 29 29" xmlns="http://www.w3.org/2000/svg"><rect width="29" height="29" fill="#fff"/><text x="2" y="16" font-size="5">QR</text></svg>`; }
const tagUrl = (c, red) => `${PAGE_URL}?flag=${c.id}${red ? '&red=1' : ''}`;
export function pcardHtml(c, sheet, red) { const hasLevel = c.numericLevels && c.reorder != null && c.fill > c.reorder; const num = hasLevel ? c.reorder | 0 : null;
  const uEn = unitOf(c, num ?? 2, 'en').toUpperCase(), uEs = unitOf(c, num ?? 2, 'es');
  const instr = red ? `COMPLETELY OUT?<span class="act">→ SCAN THIS CARD NOW</span><span class="es">¿Se acabó por completo? → Escanea esta tarjeta ahora</span>` : num != null ? `ONLY <span class="big">${num}</span> ${uEn} LEFT?<span class="act">→ SCAN THIS CARD</span><span class="es">¿Solo quedan ${num} ${uEs}? → Escanea esta tarjeta</span>` : `OPENING THE LAST ${/box/i.test(uEn) ? 'BOX' : 'PACK'}?<span class="act">→ SCAN THIS CARD</span><span class="es">¿Abriendo ${/box/i.test(uEn) ? 'la última caja' : 'el último paquete'}? → Escanea esta tarjeta</span>`;
  const zoneTxt = c.zone === 'Unassigned' ? '—' : (c.zone || '').toUpperCase();
  const foot = red ? `RED CARD · lives at the very bottom of the back bin · tarjeta roja · al fondo del bin de atrás` : (num != null ? `Reorder at · Pedir a ${num} — Fill to · Llenar a ${c.fill | 0} — orders ${c.suggested}` : `<span class="dash">Reorder at · Pedir a —</span> — card says · la tarjeta dice ${esc(c.orderQtyRaw)}`);
  return `<div class="pcard ${sheet ? 'sheet' : ''} ${red ? 'red' : ''}"><div class="stencil"><span>${esc(zoneTxt)}${c.slot ? ` · ${esc(c.slot)}` : ''}</span><span class="vend">${esc(c.vendor)}</span></div><div class="pname">${esc(shortName(c, 'en'))}</div><div class="pbody"><div class="instr">${instr}</div><div class="qr">${qrSvg(tagUrl(c, red))}</div></div><div class="pfoot"><span>${foot}</span><span>#${c.id}${red ? 'R' : ''} · v2 · ${fmtMD(M.today, false)}</span></div></div>`; }
function printGroup(v) { const ids = vendorCards(v).filter(c => !L.printed[c.id]).map(c => c.id); if (!ids.length) return; printCards(ids, S.printFmt === 'sheet' || v === 'Grove' ? 'sheet' : 'card'); }
export function printCards(ids, fmt) { const area = $('#printArea'); const red = fmt === 'red'; area.className = `fmt-${red ? 'card' : fmt}`; area.innerHTML = ids.map(id => pcardHtml(byId(id), fmt === 'sheet', red)).join(''); const when = new Date().toISOString(); const done = () => { ids.forEach(id => { L.printed[id] = when; }); saveL(); render(); toast(ES() ? `${ids.length} tarjetas enviadas a la impresora` : `${ids.length} cards sent to the printer`); window.removeEventListener('afterprint', done); }; window.addEventListener('afterprint', done); window.print(); }
function renderPrint() { const es = ES(); const el = $('#view-print'); const c = byId(S.printSel) || cards()[0]; if (!c) { el.innerHTML = ''; return; } const vendors = [...new Set(cards().map(x => x.vendor))].sort((a, b) => vendorCards(b).length - vendorCards(a).length); const need = cards().filter(x => !L.printed[x.id]).length;
  let h = `<div class="print-grid"><div class="pq"><div class="pqh"><b>${t('reprint')} · ${need}</b> <span class="muted">— ${need === cards().length ? (es ? 'todas llevan la URL antigua de la página · en orden de estante' : 'every printed card still carries the old page URL · shelf order') : (es ? `${cards().length - need} ya impresas desde esta página · el punto naranja marca las pendientes` : `${cards().length - need} printed from this page · the orange dot marks what is left`)}</span></div><div class="scroll">`;
  vendors.forEach(v => { const vc = vendorCards(v).sort((a, b) => ((L.printed[b.id] ? 0 : 1) - (L.printed[a.id] ? 0 : 1)) || bySlot(a, b)); const n = vc.filter(x => !L.printed[x.id]).length; h += `<div class="grp ${n ? 'reprint' : ''}">${esc(v)} <span class="n">${n ? `${n} ${es ? 'por imprimir' : 'to print'}` : `✓ ${t('printed')}`} · ${v === 'Grove' ? t('fmtSheet') : t('fmtCard')}</span><button class="tb-btn btn-sm" data-printv="${esc(v)}" ${n ? '' : 'disabled'}>${t('print')} ${n || ''}</button></div><ul>`; vc.forEach(x => h += `<li aria-selected="${x.id === S.printSel}" data-p="${x.id}"><i class="np ${L.printed[x.id] ? 'done' : ''}"></i>${picHtml(x)}<span>${nameHtml(x)}</span>${slotChip(x)}</li>`); h += `</ul>`; });
  h += `</div></div>`;
  const fmt = S.printFmt; const caps = { card: es ? 'Se imprime en cartulina 6×4 in · la tarjeta verde va entre los dos bins · el QR abre la Tag' : 'Prints on 6×4 in card stock · the green card sits between the two bins · the QR opens the Tag', red: es ? 'Tarjeta roja 6×4 · al fondo del bin de atrás · escanearla = se acabó por completo, que nunca debería pasar' : 'Red card 6×4 · lives at the very bottom of the back bin · scanning it means completely out, which should never happen', sheet: es ? 'Hoja completa 8.5×11 · una por bin de bolsas Grove · se lee desde el otro lado del cuarto' : 'Full sheet 8.5×11 · one per Grove bag bin · readable from across the room' };
  h += `<div class="pv"><div class="pv-head"><div class="tabs">${[['card', 'fmtCard'], ['red', 'fmtRed'], ['sheet', 'fmtSheet']].map(([k, l]) => `<button class="tab" data-fmt="${k}" aria-selected="${fmt === k}">${t(l)}</button>`).join('')}</div><button class="tb-btn btn-primary" id="printOne">${t('print')} · ${esc(shortName(c))}</button><span class="muted" style="font-size:13px">${es ? 'Una plantilla, tres formatos.' : 'One template, three formats.'}</span></div>
  <div class="stage"><div class="scaled" id="pstage">${pcardHtml(c, fmt === 'sheet', fmt === 'red')}</div></div><div class="cap">${caps[fmt]}</div></div></div>`;
  el.innerHTML = h; $('#printOne', el).onclick = () => printCards([c.id], fmt); wire(el); requestAnimationFrame(fitStages); }
function fitStages() { $$('.stage').forEach(st => { const inner = st.querySelectorAll('.scaled'); const avail = st.clientWidth - 44; let total = 0; inner.forEach(i => total += (i.firstElementChild.offsetWidth || 576)); const gap = (inner.length - 1) * 20; const sc = Math.min(1, (avail - gap) / total); inner.forEach(i => { const w = i.firstElementChild.offsetWidth, hh = i.firstElementChild.offsetHeight; i.style.transform = `scale(${sc})`; i.style.width = (w * sc) + 'px'; i.style.height = (hh * sc) + 'px'; }); }); }
window.addEventListener('resize', () => { if (S.view === 'print') fitStages(); });

// ---------- GROVE ----------
function renderGrove() { const es = ES(); const el = $('#view-grove'); const gc = vendorCards('Grove'); const req = gc.filter(c => state(c) === 'requested' || L.groveOrdered[c.id]), bins = gc.filter(c => !req.includes(c));
  el.innerHTML = `<div class="board" style="margin-top:0"><div class="board-h"><h2>Grove</h2><span class="when">${es ? 'Bolsas personalizadas · plazo <b>75 días</b> · mínimo 2,500 por tamaño · Damon pide por correo' : 'Custom bags · <b>75-day</b> lead · minimum 2,500 per size · Damon orders by email'}</span></div><div class="lanes two">${lane('r', 1, t('reqLane'), req.length, t('reqSub'), req.map(c => icard(c, 'req')).join(''), '', es ? 'Ninguna solicitud abierta' : 'No open requests')}${lane('n', 2, t('binLane'), bins.length, t('binSub'), bins.map(c => icard(c, 'bin')).join(''))}</div></div><details class="tech" style="margin-top:12px"><summary>${es ? 'Cómo funcionan los bins' : 'How bins work'}</summary><p class="muted" style="font-size:14px;max-width:80ch;margin:0">${es ? 'Cada bin (~200 bolsas) lleva una tarjeta de hoja completa. Abrir un bin = escanear su tarjeta; a mano = bins sellados; punto de pedido = ritmo × (75 + 30 días). Los conteos viven en este navegador hasta la próxima versión.' : 'Each bin (~200 bags) carries a full-sheet card. Opening a bin = scanning its card; on hand = sealed bins; reorder point = burn rate × (75 + 30 days). Counts live in this browser until the next build.'}</p></details>`; wire(el); }

// ---------- TAG ----------
const TAG_STATES = [['queued', ['Queued', 'En la lista']], ['already', ['Already on the list', 'Ya está en la lista']], ['held', ['Waiting for the check day', 'Esperando la revisión']], ['on-order', ['On order', 'Ya está pedido']], ['requested', ['Requested from Damon', 'Solicitado a Damon']], ['out', ['Red card · OUT', 'Tarjeta roja · SE ACABÓ']], ['bad', ['Not saved', 'No se guardó']], ['unknown', ['Card not recognised', 'Tarjeta no reconocida']], ['removed', ['Removed from the list', 'Quitado de la lista']]];
let tagTimer = null;
export const tagES = () => S.tag.lang ? S.tag.lang === 'es' : ES();
export function renderTag(handlers = {}) { const es = tagES(); const tl = es ? 'es' : 'en'; const el = $('#view-tag'); const c = byId(S.tag.card) || cards()[0]; const st = S.tag.state; const qty = S.tag.qty ?? (c && c.inCart ? c.inCart.qty : (c ? c.suggested : 0)); const nm = c ? shortName(c, tl) : ''; const un = c ? unitOf(c, qty, tl) : ''; const vd = c ? M.vendors[c.vendor] : null;
  const Lx = (en, esx) => es ? esx : en, O = (esx, en) => es ? en : esx;
  const fD = s => fmtD(s, es), fMD = s => fmtMD(s, es);
  const goes = vd && vd.lane === 'cart' && c.vendor !== 'Sticker Mule' ? Lx(`next check ${fD(M.d1)}`, `próxima revisión ${fD(M.d1)}`) : (c && c.vendor === 'Grove' ? Lx('Damon gets an email', 'Damon recibe un correo') : Lx('ordered when one runs out', 'se pide cuando uno se acaba'));
  const rcv = c ? orderedMap(L.receipts)[c.id] : null; const rc = (rcv && L.receipts[rcv]) || { expected: addDays(M.today, c ? leadOf(c) : 1) }; const lateOrder = M.today > rc.expected; const since = c && c.inCart ? fmtTS(c.inCart.addedAt, es) : Lx('today', 'hoy');
  const told = !!(c && S.tag.told[c.id]);
  const band = { queued: ['#3b7a57', '#fff', Lx('Queued', 'En la lista'), O('En la lista', 'Queued'), String(qty), un, nm, `${Lx('for', 'para')} ${c?.vendor} · ${goes}`],
    already: ['#3b7a57', '#fff', Lx('Already on the list ✓', 'Ya está en la lista ✓'), O('Ya está en la lista', 'Already on the list'), String(qty), un, nm, `${Lx('since', 'desde')} ${since} · ${Lx('for', 'para')} ${c?.vendor}`],
    held: ['#3b7a57', '#fff', Lx('Counted ✓ · waiting for the check day', 'Contado ✓ · esperando la revisión'), O('Contado · esperando la revisión', 'Counted · waiting for the check day'), String(qty), un, nm, `⏱ ${c?.vendor} · ${goes}`],
    out: ['#b5493a', '#fff', Lx('OUT · red card', 'SE ACABÓ · tarjeta roja'), O('SE ACABÓ · tarjeta roja', 'OUT · red card'), '0', un, nm, Lx('The desk has been told — it orders today', 'Ya se avisó al escritorio — se pide hoy')],
    'on-order': ['#62758d', '#fff', Lx('Already on order', 'Ya está pedido'), O('Ya está pedido', 'Already on order'), fMD(rc.expected), lateOrder ? Lx('was due', 'se esperaba') : Lx('arrives', 'llega'), nm, `${Lx('for', 'para')} ${c?.vendor}${lateOrder ? ` · ${Lx('not here yet', 'todavía no llega')}` : ''}`],
    requested: ['#62758d', '#fff', Lx('Requested from Damon', 'Solicitado a Damon'), O('Solicitado a Damon', 'Requested from Damon'), '✉', '', nm, Lx('Damon has been emailed', 'Ya se le escribió a Damon')],
    bad: ['#b5493a', '#fff', Lx('Not saved', 'No se guardó'), O('No se guardó', 'Not saved'), '!', '', nm, Lx('The farm server did not answer', 'El servidor de la granja no respondió')],
    unknown: ['#8f5d0a', '#fff', Lx('Card not recognised', 'Tarjeta no reconocida'), O('Tarjeta no reconocida', 'Card not recognised'), '?', '', '', Lx('Retired or reprinted card', 'Tarjeta retirada o reimpresa')],
    removed: ['#5c6b62', '#fff', Lx('Removed from the list', 'Quitado de la lista'), O('Quitado de la lista', 'Removed from the list'), '0', '', nm, Lx('Nothing will be ordered', 'No se pedirá nada')] }[st] || ['#5c6b62', '#fff', st, '', '', '', nm, ''];
  const urgentBtn = ['out', told ? Lx('Told the desk ✓', 'Avisado al escritorio ✓') : Lx('Tell the desk it’s urgent', 'Avisar al escritorio: es urgente'), 'urgent', told];
  const btns = { queued: [['out', Lx('Need more? +1', '¿Falta más? +1'), 'plus']], already: [['out', Lx('+1 more', '+1 más'), 'plus']], held: [urgentBtn], 'on-order': [urgentBtn], requested: [], out: [], bad: [['act', Lx('Try again', 'Intentar de nuevo'), 'retry']], unknown: [['out', Lx('Scan again', 'Escanear otra vez'), 'rescan']], removed: [['out', Lx('Queue again', 'Volver a poner'), 'requeue']] }[st] || [];
  const fact = { queued: Lx('Saved ✓ — point the camera at the next card.', 'Guardado ✓ — apunta la cámara a la siguiente tarjeta.'), already: Lx('Counted ✓', 'Contado ✓'), held: Lx('It goes on the next check by itself.', 'Va solo en la próxima revisión.'), 'on-order': lateOrder ? Lx('It has not arrived yet.', 'Todavía no ha llegado.') : Lx('It is already coming.', 'Ya viene en camino.'), requested: Lx('Nothing else to do.', 'Nada más que hacer.'), out: Lx('Saved ✓. This should never happen — the desk orders it today and raises the level.', 'Guardado ✓. Esto no debería pasar — el escritorio lo pide hoy y sube el nivel.'), bad: Lx('Not saved. Tap Try again.', 'No se guardó. Toca Intentar de nuevo.'), unknown: Lx('Show this card to Boss.', 'Muéstrala a Boss.'), removed: Lx('Tapped Undo by mistake? Queue again.', '¿Tocaste Deshacer sin querer? Vuelve a ponerla.') }[st] || '';
  const undoable = (st === 'queued' || st === 'out') && (S.tag.added || S.tag.last === 'plus'); const undoLbl = S.tag.last === 'plus' ? Lx('Undo +1', 'Deshacer +1') : Lx('Undo', 'Deshacer');
  const closeBtn = S.tag.live ? '' : `<button class="tlink" data-tag="close">${Lx('Close', 'Cerrar')}</button>`;
  el.innerHTML = `<div class="tag-wrap"><div class="phone" aria-label="Phone"><div class="notch"></div><div class="screen">
    <div class="band" style="background:${band[0]};color:${band[1]}"><button class="lang" data-tag="lang" aria-label="${Lx('Español', 'English')}">${es ? 'EN' : 'ES'}</button><div class="verb">${esc(band[2])}<small>${esc(band[3])}</small></div><div class="num">${esc(band[4])}${band[5] ? `<small>${esc(band[5])}</small>` : ''}</div>${band[6] ? `<div class="obj">${esc(band[6])}</div>` : ''}<div class="for">${esc(band[7])}</div></div>
    <div class="tbody">${st === 'unknown' || !c ? '' : `<div class="tcard"><div><div class="st">${esc((c.zone || '').toUpperCase())}${c.slot ? ` · ${esc(c.slot)}` : ''}</div><div class="tn">${esc(c.item)}</div><div class="tl2">${c.numericLevels ? `${Lx('Reorder at', 'Pedir a')} ${c.reorder | 0} · ${Lx('Fill to', 'Llenar a')} ${c.fill | 0}` : `${Lx('card says', 'la tarjeta dice')} ${esc(c.orderQtyRaw)}`}</div></div><img src="${esc(THUMB(c))}" alt="" referrerpolicy="no-referrer"></div>`}
    <div class="fact">${fact}</div>
    <div class="tbtns">${btns.map(([k, l, fn, dis]) => `<button class="tbtn ${k === 'act' ? 'act' : ''}" data-tag="${fn}" ${dis ? 'disabled' : ''}>${esc(l)}</button>`).join('')}${undoable ? `<button class="tundo" id="tundo" data-tag="undo" style="--pct:${(S.tag.undoLeft / 30 * 100) | 0}%">${undoLbl} · ${S.tag.undoLeft} s</button>` : ''}${closeBtn}</div>
    <div class="tfoot">${Lx('Scan logged', 'Escaneo registrado')} · ${fmtTS(nowISO(), es)} · ${Lx('no name needed', 'sin nombre')}</div></div></div></div>
  ${S.tag.live ? '' : `<div class="tag-side"><h3>${Lx('The Tag: what a worker sees after a scan', 'La Tag: lo que ve un trabajador al escanear')}</h3><p>${Lx('This is a preview. The real Tag opens when a printed card is scanned (this page with ?flag=<id>); it shows one language at a time, the other in small under the heading, needs no tap on success, and never places an order. Scans are anonymous. The red card at the bottom of the back bin has its own QR.', 'Esto es una vista previa. La Tag real se abre al escanear una tarjeta impresa (esta página con ?flag=<id>); muestra un idioma a la vez, no requiere ningún toque si todo salió bien y nunca hace un pedido. Los escaneos son anónimos. La tarjeta roja al fondo del bin de atrás tiene su propio QR.')}</p>
  <div class="eyebrow" style="margin-bottom:6px">${Lx('Preview state', 'Estado de vista previa')}</div><div class="states">${TAG_STATES.map(([k, l]) => `<button class="chip" aria-pressed="${st === k}" data-tagstate="${k}">${l[es ? 1 : 0]}</button>`).join('')}</div>
  <div class="eyebrow" style="margin-bottom:6px">${Lx('Card', 'Tarjeta')}</div><div class="states">${cards().slice(0, 8).map(x => `<button class="chip" aria-pressed="${S.tag.card === x.id}" data-tagcard="${x.id}">${esc(shortName(x, tl).slice(0, 26))}</button>`).join('')}</div></div>`}</div>`;
  $$('[data-tagstate]', el).forEach(b => b.onclick = () => { S.tag.state = b.dataset.tagstate; S.tag.undoLeft = 30; S.tag.added = b.dataset.tagstate === 'queued'; render(); });
  $$('[data-tagcard]', el).forEach(b => b.onclick = () => { S.tag.card = +b.dataset.tagcard; S.tag.qty = null; S.tag.state = byId(S.tag.card).inCart ? 'already' : 'queued'; render(); });
  $$('[data-tag]', el).forEach(b => b.onclick = () => { const k = b.dataset.tag; if (k === 'lang') { S.tag.lang = tagES() ? 'en' : 'es'; render(); return; } if (handlers[k]) handlers[k](); else toast(k); });
  clearInterval(tagTimer); tagTimer = null; if (undoable && $('#tundo')) { tagTimer = setInterval(() => { const btn = $('#tundo'); if (!btn) { clearInterval(tagTimer); tagTimer = null; return; } S.tag.undoLeft = Math.max(0, S.tag.undoLeft - 1); btn.style.setProperty('--pct', (S.tag.undoLeft / 30 * 100) + '%'); btn.textContent = btn.textContent.replace(/\d+ s$/, S.tag.undoLeft + ' s'); if (S.tag.undoLeft === 0) { btn.disabled = true; btn.style.opacity = .5; clearInterval(tagTimer); tagTimer = null; } }, 1000); } }
let tagHandlers = {};
export function setTagHandlers(h) { tagHandlers = h; }

// ---------- render ----------
export function render() { if (!M) return; if (S.tag.live) { VIEWS.forEach(k => $('#view-' + k).hidden = (k !== 'tag')); renderTag(tagHandlers); return; }
  renderTabs(); VIEWS.forEach(k => $('#view-' + k).hidden = (S.view !== k));
  if (S.view === 'order') renderOrder(); if (S.view === 'cards') renderCards(); if (S.view === 'print') renderPrint(); if (S.view === 'grove') renderGrove(); if (S.view === 'tag') renderTag(tagHandlers); renderActbar(); }
export { shortName, unitOf, fmtD, fmtMD, fmtTS };
