#!/usr/bin/env node
/**
 * stamp-modules — content-hash the ES module graph via generated import maps.
 *
 * WHY THIS EXISTS
 * ---------------
 * Pages load a module entry with a hand-bumped cache buster:
 *
 *     <script type="module" src="../js/modules/index.js?v=6"></script>
 *
 * That query busts the ENTRY ONLY. Every module it imports uses a bare
 * relative specifier (`import { x } from './widgets.js'`), which carries no
 * version at all — so a browser is free to pair a freshly fetched entry with
 * a sibling it cached ten minutes ago. When the new entry imports a symbol the
 * cached sibling does not export yet, the named import fails, and a failed
 * named import takes down the ENTIRE module graph. The page renders nothing.
 *
 * That is not hypothetical: it took the production dashboard down on
 * 2026-08-12 (commit 28af5986, "does not provide an export named
 * updateDataWidgets"). Bumping the service worker's CACHE_VERSION does not fix
 * it — the worker drops its caches and then refetches through the browser HTTP
 * cache, faithfully repopulating a brand-new cache with the old deploy's files.
 *
 * WHAT IT DOES
 * ------------
 * Walks each page's module graph, hashes every file by content, and writes an
 * import map into the page that redirects each specifier to a hashed URL:
 *
 *     "../js/modules/widgets.js" -> "../js/modules/widgets.js?h=9f3c1a20"
 *
 * A deploy that changes a module changes its hash, so the URL is one the
 * browser has never seen and cannot answer from cache. Files that did not
 * change keep their URL and stay cached.
 *
 * WHY IMPORT MAPS RATHER THAN HASHED FILENAMES
 * --------------------------------------------
 * This project deploys the repo directly to GitHub Pages with no build step.
 * Hashed filenames would mean committing generated duplicates of every module.
 * An import map keeps one copy of each file, touches only the HTML, and — on a
 * browser that does not support import maps — is ignored, leaving today's
 * behaviour rather than a broken page.
 *
 * KEYS ARE RELATIVE ON PURPOSE
 * ----------------------------
 * Import-map keys resolve against the DOCUMENT base URL. A key written
 * relative to the page ("../js/modules/utils.js" from src/pages/) resolves
 * identically under the GitHub Pages prefix (/rogue-origin-apps/src/pages/)
 * and under a local server rooted at src/. An absolute key would match one and
 * silently miss the other — and a silent miss is the bug this file exists to
 * prevent.
 *
 * USAGE
 *   node tools/stamp-modules.mjs           # rewrite pages
 *   node tools/stamp-modules.mjs --check   # exit 1 if any page is stale
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve, posix } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Walk up from this file until src/pages turns up, so the script can be moved. */
function findRepoRoot(from) {
  let dir = from;
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, 'src', 'pages'))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error(`stamp-modules: could not locate src/pages above ${from}`);
}

const REPO_ROOT = findRepoRoot(dirname(fileURLToPath(import.meta.url)));
const PAGES_DIR = join(REPO_ROOT, 'src', 'pages');
const HASH_LENGTH = 8;

// Markers must stay byte-stable forever. They are how a regenerate finds and
// replaces the previous block; when the text drifts the old block stops
// matching and a SECOND import map is appended — which browsers do not
// reliably honour. So no paths, versions or dates inside the marker itself.
// (Learned the hard way: moving this script from tools/build/ to tools/ once
// changed the marker and duplicated the block on all 15 pages.)
const START_MARKER = '<!-- module-hashes:start -->';
const END_MARKER = '<!-- module-hashes:end -->';
const GENERATED_NOTE = '<!-- generated by stamp-modules — do not edit by hand -->';

const checkOnly = process.argv.includes('--check');
const warnings = [];

/**
 * Static `import`/`export ... from '...'`, plus dynamic `import('...')`.
 *
 * The clause may span lines — most of this codebase imports a braced list one
 * name per line — so the gap before `from` must allow newlines. A semicolon is
 * the statement boundary and is the one thing it must not cross.
 */
const STATIC_IMPORT = /(?:^|\n)\s*(?:import|export)\b[^;]*?\sfrom\s*['"]([^'"]+)['"]/g;
const BARE_IMPORT = /(?:^|\n)\s*import\s*['"]([^'"]+)['"]/g;
const DYNAMIC_IMPORT = /\bimport\s*\(\s*['"]([^'"]+)['"]\s*\)/g;

function specifiersIn(source) {
  const found = new Set();
  for (const re of [STATIC_IMPORT, BARE_IMPORT, DYNAMIC_IMPORT]) {
    re.lastIndex = 0;
    let match;
    while ((match = re.exec(source)) !== null) found.add(match[1]);
  }
  return [...found];
}

/** Only relative specifiers are ours to stamp; bare and absolute URLs are not. */
function isLocalSpecifier(spec) {
  return spec.startsWith('./') || spec.startsWith('../') || spec.startsWith('/');
}

/**
 * Walk the module graph from a set of entry files.
 * @returns {Set<string>} absolute paths of every module reachable, entries included
 */
function collectGraph(entryPaths) {
  const seen = new Set();
  const queue = [...entryPaths];

  while (queue.length) {
    const file = queue.pop();
    if (seen.has(file) || !existsSync(file)) continue;
    seen.add(file);

    let source;
    try {
      source = readFileSync(file, 'utf8');
    } catch {
      continue;
    }

    for (const spec of specifiersIn(source)) {
      if (!isLocalSpecifier(spec)) continue;
      // A specifier may already carry a query; resolve against the bare path.
      const bare = spec.split('?')[0].split('#')[0];
      const target = resolve(dirname(file), bare);
      if (existsSync(target) && statSync(target).isFile()) {
        queue.push(target);
      } else {
        warnings.push(`  unresolved: ${spec}  (from ${relative(REPO_ROOT, file)})`);
      }
    }
  }
  return seen;
}

/**
 * Hash file contents with line endings normalised.
 *
 * Git hands Windows checkouts CRLF and Linux checkouts LF for the same commit.
 * Hashing raw bytes would therefore give the same source two different hashes
 * depending on who ran the generator — rewriting every page and conflicting on
 * every merge, without any code having changed. Browsers do not care about the
 * line endings, and neither should the cache key.
 */
function contentHash(file) {
  const normalised = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  return createHash('sha256').update(normalised, 'utf8').digest('hex').slice(0, HASH_LENGTH);
}

/** Page-relative POSIX path, the form an import-map key must take. */
function keyFor(pageDir, moduleFile) {
  const rel = relative(pageDir, moduleFile).split('\\').join('/');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

function buildImportMap(pageFile) {
  const html = readFileSync(pageFile, 'utf8');
  const pageDir = dirname(pageFile);

  const entryRe = /<script[^>]*\btype=["']module["'][^>]*\bsrc=["']([^"']+)["']/g;
  const entries = [];
  let match;
  while ((match = entryRe.exec(html)) !== null) {
    const bare = match[1].split('?')[0].split('#')[0];
    if (!isLocalSpecifier(bare)) continue;
    const abs = resolve(pageDir, bare);
    if (existsSync(abs)) entries.push(abs);
    else warnings.push(`  missing entry: ${match[1]}  (in ${relative(REPO_ROOT, pageFile)})`);
  }

  if (!entries.length) return { html, map: null, moduleCount: 0 };

  const graph = collectGraph(entries);
  const imports = {};
  // Entries are loaded via src= and are never remapped, but including them is
  // harmless and covers the case where one module imports another page's entry.
  for (const file of [...graph].sort()) {
    const key = keyFor(pageDir, file);
    imports[key] = `${key}?h=${contentHash(file)}`;
  }

  return { html, map: { imports }, moduleCount: graph.size };
}

/** Inject or replace the generated block, immediately above the first module script. */
function applyImportMap(html, map) {
  const block = [
    START_MARKER,
    GENERATED_NOTE,
    '<script type="importmap">',
    JSON.stringify(map, null, 2),
    '</script>',
    END_MARKER
  ].join('\n');

  // Global: strip EVERY previously generated block before inserting, so a page
  // that somehow acquired two can never keep one behind.
  const existing = new RegExp(
    `[ \\t]*${escapeRe(START_MARKER)}[\\s\\S]*?${escapeRe(END_MARKER)}\n?`, 'g'
  );
  const stripped = html.replace(existing, '');

  const firstModule = stripped.search(/[ \t]*<script[^>]*\btype=["']module["']/);
  if (firstModule === -1) return stripped;
  html = stripped;

  // Preserve the indentation of the script tag we are inserting above.
  const lineStart = html.lastIndexOf('\n', firstModule) + 1;
  const indent = (html.slice(lineStart, firstModule).match(/^[ \t]*/) || [''])[0];
  const indented = block.split('\n').map((l) => (l ? indent + l : l)).join('\n');
  return `${html.slice(0, lineStart) + indented}\n${html.slice(lineStart)}`;
}

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// ---------------------------------------------------------------------------

const pages = readdirSync(PAGES_DIR)
  .filter((f) => f.endsWith('.html'))
  .map((f) => join(PAGES_DIR, f))
  .sort();

let changed = 0;
let stamped = 0;
const stale = [];

for (const page of pages) {
  const { html, map, moduleCount } = buildImportMap(page);
  if (!map) continue;

  const next = applyImportMap(html, map);
  stamped++;

  // A page must end up with exactly one import map. More than one is not
  // reliably honoured by browsers, and would silently leave part of the graph
  // unhashed — the precise failure this tool exists to prevent.
  const mapCount = (next.match(/<script[^>]*\btype=["']importmap["']/g) || []).length;
  if (mapCount !== 1) {
    console.error(
      `\nstamp-modules: ${relative(REPO_ROOT, page)} would have ${mapCount} import maps ` +
      '(expected exactly 1). Refusing to write.'
    );
    process.exit(1);
  }

  if (next !== html) {
    stale.push(relative(REPO_ROOT, page).split('\\').join('/'));
    if (!checkOnly) writeFileSync(page, next);
    changed++;
  }
  const name = relative(REPO_ROOT, page).split('\\').join('/');
  console.log(`  ${next !== html ? '*' : ' '} ${name.padEnd(34)} ${moduleCount} modules`);
}

if (warnings.length) {
  console.warn('\nwarnings:');
  for (const w of [...new Set(warnings)]) console.warn(w);
}

if (checkOnly && changed) {
  console.error(`\nstamp-modules --check: ${changed} page(s) have stale import maps:`);
  for (const p of stale) console.error(`  ${p}`);
  console.error('Run: npm run stamp');
  process.exit(1);
}

console.log(
  `\nstamp-modules: ${stamped} page(s) with module entries, ` +
  `${changed} ${checkOnly ? 'stale' : 'updated'}.`
);
