#!/usr/bin/env node
/**
 * stamp-modules — content-hash the ES module graph via generated import maps.
 *
 * WHY THIS EXISTS
 * ---------------
 * Pages used to load a module entry with a hand-bumped cache buster:
 *
 *     <script type="module" src="../js/modules/index.js?v=6"></script>
 *
 * That query busted the ENTRY ONLY. Every module it imports uses a bare
 * relative specifier (`import { x } from './widgets.js'`), which carried no
 * version at all — so a browser was free to pair a freshly fetched entry with
 * a sibling it cached ten minutes ago. When the new entry imports a symbol the
 * cached sibling does not export yet, the named import fails, and a failed
 * named import takes down the ENTIRE module graph. The page renders nothing.
 *
 * Worse, several pages (orders.html, barcode.html) had module entries with no
 * cache buster at all, so those entries were pinned until the HTTP cache
 * expired — the hand-bump script only ever incremented a ?v= that was already
 * there, and it could only see files named directly in the HTML.
 *
 * That is not hypothetical: it took the production dashboard down on
 * 2026-08-12 (commit 28af5986, "does not provide an export named
 * updateDataWidgets"). Bumping the service worker's CACHE_VERSION does not fix
 * it — the worker drops its caches and then refetches through the browser HTTP
 * cache, faithfully repopulating a brand-new cache with the old deploy's files.
 *
 * WHAT IT DOES
 * ------------
 * Walks each page's module graph, hashes every file by content, and covers
 * both halves of the graph:
 *
 *   imported modules  an import map redirects each specifier to a hashed URL
 *                     "../js/modules/widgets.js"
 *                       -> "../js/modules/widgets.js?h=9f3c1a20"
 *
 *   entry tags        rewritten in place, because an import map governs
 *                     specifiers inside modules and never a src attribute
 *                     <script type="module" src="../js/modules/index.js?h=761eddc0">
 *
 * A deploy that changes a module changes its hash, so the URL is one the
 * browser has never seen and cannot answer from cache. Files that did not
 * change keep their URL and stay cached.
 *
 * Module entries are therefore on ?h= and no longer on ?v=. Classic <script>
 * and <link> tags keep ?v=N and remain the pre-commit hook's job — the hook
 * can see those because they are named directly in the HTML, which is exactly
 * what it cannot do for an imported module.
 *
 * WHY IMPORT MAPS RATHER THAN HASHED FILENAMES
 * --------------------------------------------
 * This project deploys the repo directly to GitHub Pages with no build step.
 * Hashed filenames would mean committing generated duplicates of every module.
 * An import map keeps one copy of each file, touches only the HTML, and — on a
 * browser that does not support import maps — is ignored, leaving today's
 * behaviour rather than a broken page.
 *
 * KEYS ARE RELATIVE ON PURPOSE
 * ----------------------------
 * Import-map keys resolve against the DOCUMENT base URL. A key written
 * relative to the page ("../js/modules/utils.js" from src/pages/) resolves
 * identically under the GitHub Pages prefix (/rogue-origin-apps/src/pages/)
 * and under a local server rooted at src/. An absolute key would match one and
 * silently miss the other — and a silent miss is the bug this file exists to
 * prevent.
 *
 * USAGE
 *   node tools/stamp-modules.mjs           # rewrite pages
 *   node tools/stamp-modules.mjs --check   # exit 1 if any page is stale
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve, posix } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Walk up from this file until src/pages turns up, so the script can be moved. */
function findRepoRoot(from) {
  let dir = from;
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, 'src', 'pages'))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error(`stamp-modules: could not locate src/pages above ${from}`);
}

const REPO_ROOT = findRepoRoot(dirname(fileURLToPath(import.meta.url)));
const PAGES_DIR = join(REPO_ROOT, 'src', 'pages');
const HASH_LENGTH = 8;

// Markers must stay byte-stable forever. They are how a regenerate finds and
// replaces the previous block; when the text drifts the old block stops
// matching and a SECOND import map is appended — which browsers do not
// reliably honour. So no paths, versions or dates inside the marker itself.
// (Learned the hard way: moving this script from tools/build/ to tools/ once
// changed the marker and duplicated the block on all 15 pages.)
const START_MARKER = '<!-- module-hashes:start -->';
const END_MARKER = '<!-- module-hashes:end -->';
const GENERATED_NOTE = '<!-- generated by stamp-modules — do not edit by hand -->';

const checkOnly = process.argv.includes('--check');
const warnings = [];

/**
 * Static `import`/`export ... from '...'`, plus dynamic `import('...')`.
 *
 * The clause may span lines — most of this codebase imports a braced list one
 * name per line — so the gap before `from` must allow newlines. A semicolon is
 * the statement boundary and is the one thing it must not cross.
 */
const STATIC_IMPORT = /(?:^|\n)\s*(?:import|export)\b[^;]*?\sfrom\s*['"]([^'"]+)['"]/g;
const BARE_IMPORT = /(?:^|\n)\s*import\s*['"]([^'"]+)['"]/g;
const DYNAMIC_IMPORT = /\bimport\s*\(\s*['"]([^'"]+)['"]\s*\)/g;

function specifiersIn(source) {
  const found = new Set();
  for (const re of [STATIC_IMPORT, BARE_IMPORT, DYNAMIC_IMPORT]) {
    re.lastIndex = 0;
    let match;
    while ((match = re.exec(source)) !== null) found.add(match[1]);
  }
  return [...found];
}

/** Only relative specifiers are ours to stamp; bare and absolute URLs are not. */
function isLocalSpecifier(spec) {
  return spec.startsWith('./') || spec.startsWith('../') || spec.startsWith('/');
}

/**
 * Walk the module graph from a set of entry files.
 * @returns {Set<string>} absolute paths of every module reachable, entries included
 */
function collectGraph(entryPaths) {
  const seen = new Set();
  const queue = [...entryPaths];

  while (queue.length) {
    const file = queue.pop();
    if (seen.has(file) || !existsSync(file)) continue;
    seen.add(file);

    let source;
    try {
      source = readFileSync(file, 'utf8');
    } catch {
      continue;
    }

    for (const spec of specifiersIn(source)) {
      if (!isLocalSpecifier(spec)) continue;
      // A specifier may already carry a query; resolve against the bare path.
      const bare = spec.split('?')[0].split('#')[0];
      const target = resolve(dirname(file), bare);
      if (existsSync(target) && statSync(target).isFile()) {
        queue.push(target);
      } else {
        warnings.push(`  unresolved: ${spec}  (from ${relative(REPO_ROOT, file)})`);
      }
    }
  }
  return seen;
}

/**
 * Hash file contents with line endings normalised.
 *
 * Git hands Windows checkouts CRLF and Linux checkouts LF for the same commit.
 * Hashing raw bytes would therefore give the same source two different hashes
 * depending on who ran the generator — rewriting every page and conflicting on
 * every merge, without any code having changed. Browsers do not care about the
 * line endings, and neither should the cache key.
 */
function contentHash(file) {
  const normalised = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  return createHash('sha256').update(normalised, 'utf8').digest('hex').slice(0, HASH_LENGTH);
}

/** Page-relative POSIX path, the form an import-map key must take. */
function keyFor(pageDir, moduleFile) {
  const rel = relative(pageDir, moduleFile).split('\\').join('/');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

function buildImportMap(pageFile) {
  const html = readFileSync(pageFile, 'utf8');
  const pageDir = dirname(pageFile);

  const entryRe = /<script[^>]*\btype=["']module["'][^>]*\bsrc=["']([^"']+)["']/g;
  const entries = [];
  let match;
  while ((match = entryRe.exec(html)) !== null) {
    const bare = match[1].split('?')[0].split('#')[0];
    if (!isLocalSpecifier(bare)) continue;
    const abs = resolve(pageDir, bare);
    if (existsSync(abs)) {
      entries.push(abs);
    } else {
      // Fatal, not a warning. A module src pointing nowhere is a broken page,
      // and treating it as a warning would skip the page silently — leaving its
      // whole graph unhashed while the run still reports success.
      console.error(
        `\nstamp-modules: ${relative(REPO_ROOT, pageFile)} references a module entry ` +
        `that does not exist: ${match[1]}`
      );
      process.exit(1);
    }
  }

  if (!entries.length) return { html, map: null, moduleCount: 0 };

  const graph = collectGraph(entries);
  const imports = {};
  // Entries are loaded via src= and are never remapped, but including them is
  // harmless and covers the case where one module imports another page's entry.
  for (const file of [...graph].sort()) {
    const key = keyFor(pageDir, file);
    imports[key] = `${key}?h=${contentHash(file)}`;
  }

  return { html, map: { imports }, moduleCount: graph.size, pageDir };
}

/** Only .js and .css are stamped. See stampAssets for why not images. */
const STAMPABLE = /\.(js|mjs|css)$/i;

/**
 * Stamp every local .js and .css reference in the page with its content hash —
 * module entries, classic <script src>, and <link href> alike.
 *
 * An import map cannot reach these: it governs specifiers inside modules, never
 * a src or href attribute. So each tag is rewritten in place, REPLACING any
 * existing ?v=N. One file, one scheme, one cache entry.
 *
 * What this fixes beyond tidiness:
 *
 *   - Hand-bumped versions drift. scoreboard-v2.html asked for timer.js?v=12
 *     while scale-display.html asked for timer.js?v=10 — the same file under
 *     two cache keys, one of them indefinitely stale. A content hash is derived
 *     from the file, so every page naturally agrees.
 *   - Some references were never versioned at all: shared-base.css appeared on
 *     12 pages bare, and sw-register.js on 9. The pre-commit hook could not
 *     touch them because it only ever incremented a ?v= that already existed.
 *   - dashboard.css appears twice per page (rel=preload as=style, plus a
 *     noscript stylesheet). Hashing by resolved file path gives both the same
 *     URL, so the preload still matches the real request rather than causing a
 *     second fetch.
 *
 * Images, icons and manifest.json are deliberately left alone. Their staleness
 * is benign, and ro-logo-square.png in particular is preloaded as="image" AND
 * referenced as a bare <img src> — hashing one occurrence and not the other
 * would turn one fetch into two.
 */
function stampAssets(html, pageDir) {
  const stamp = (whole, before, url, after) => {
    const bare = url.split('?')[0].split('#')[0];
    if (!isLocalSpecifier(bare) || !STAMPABLE.test(bare)) return whole;
    const abs = resolve(pageDir, bare);
    if (!existsSync(abs)) return whole;
    return `${before}${bare}?h=${contentHash(abs)}${after}`;
  };

  return html
    .replace(/(<script[^>]*\bsrc=["'])([^"']+)(["'])/g, stamp)
    .replace(/(<link[^>]*\bhref=["'])([^"']+)(["'])/g, stamp)
    // Inline page scripts that build a <script> at runtime. scoreboard-v2.html
    // lazy-loads debug.js this way, and its hand-written ?v=2 was a second
    // cache entry for a file the page already loads eagerly. The extension and
    // existsSync checks keep this from touching anything that is not ours.
    .replace(/(\.src\s*=\s*["'])([^"']+)(["'])/g, stamp);
}

/** Inject or replace the generated block, immediately above the first module script. */
function applyImportMap(html, map) {
  const block = [
    START_MARKER,
    GENERATED_NOTE,
    '<script type="importmap">',
    JSON.stringify(map, null, 2),
    '</script>',
    END_MARKER
  ].join('\n');

  // Global: strip EVERY previously generated block before inserting, so a page
  // that somehow acquired two can never keep one behind.
  const existing = new RegExp(
    `[ \\t]*${escapeRe(START_MARKER)}[\\s\\S]*?${escapeRe(END_MARKER)}\n?`, 'g'
  );
  const stripped = html.replace(existing, '');

  const firstModule = stripped.search(/[ \t]*<script[^>]*\btype=["']module["']/);
  if (firstModule === -1) return stripped;
  html = stripped;

  // Preserve the indentation of the script tag we are inserting above.
  const lineStart = html.lastIndexOf('\n', firstModule) + 1;
  const indent = (html.slice(lineStart, firstModule).match(/^[ \t]*/) || [''])[0];
  const indented = block.split('\n').map((l) => (l ? indent + l : l)).join('\n');
  return `${html.slice(0, lineStart) + indented}\n${html.slice(lineStart)}`;
}

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// ---------------------------------------------------------------------------

const pages = readdirSync(PAGES_DIR)
  .filter((f) => f.endsWith('.html'))
  .map((f) => join(PAGES_DIR, f))
  .sort();

let changed = 0;
let stamped = 0;
const stale = [];

for (const page of pages) {
  const { html, map, moduleCount, pageDir } = buildImportMap(page);
  if (!map) continue;

  const next = stampAssets(applyImportMap(html, map), pageDir);
  stamped++;

  // A page must end up with exactly one import map. More than one is not
  // reliably honoured by browsers, and would silently leave part of the graph
  // unhashed — the precise failure this tool exists to prevent.
  const mapCount = (next.match(/<script[^>]*\btype=["']importmap["']/g) || []).length;
  if (mapCount !== 1) {
    console.error(
      `\nstamp-modules: ${relative(REPO_ROOT, page)} would have ${mapCount} import maps ` +
      '(expected exactly 1). Refusing to write.'
    );
    process.exit(1);
  }

  // Every local .js and .css reference must carry a hash. An unstamped one is
  // pinned in the browser cache until it expires — how shared-base.css sat
  // un-bustable on 12 pages, and orders.html's entries on top of that.
  const unstamped = [
    ...[...next.matchAll(/<script[^>]*\bsrc=["']([^"']+)["']/g)].map((m) => m[1]),
    ...[...next.matchAll(/<link[^>]*\bhref=["']([^"']+)["']/g)].map((m) => m[1]),
    ...[...next.matchAll(/\.src\s*=\s*["']([^"']+)["']/g)].map((m) => m[1])
  ].filter((url) => {
    const bare = url.split('?')[0].split('#')[0];
    return isLocalSpecifier(bare) && STAMPABLE.test(bare) && !/\?h=[0-9a-f]+/.test(url);
  });
  if (unstamped.length) {
    console.error(
      `\nstamp-modules: ${relative(REPO_ROOT, page)} has unstamped assets: ` +
      `${[...new Set(unstamped)].join(', ')}. Refusing to write.`
    );
    process.exit(1);
  }

  if (next !== html) {
    stale.push(relative(REPO_ROOT, page).split('\\').join('/'));
    if (!checkOnly) writeFileSync(page, next);
    changed++;
  }
  const name = relative(REPO_ROOT, page).split('\\').join('/');
  console.log(`  ${next !== html ? '*' : ' '} ${name.padEnd(34)} ${moduleCount} modules`);
}

if (warnings.length) {
  console.warn('\nwarnings:');
  for (const w of [...new Set(warnings)]) console.warn(w);
}

if (checkOnly && changed) {
  console.error(`\nstamp-modules --check: ${changed} page(s) have stale import maps:`);
  for (const p of stale) console.error(`  ${p}`);
  console.error('Run: npm run stamp');
  process.exit(1);
}

console.log(
  `\nstamp-modules: ${stamped} page(s) with module entries, ` +
  `${changed} ${checkOnly ? 'stale' : 'updated'}.`
);
