-- 0022 harvest_lots — the 2026 lot stage board.
--
-- Moved off the Claude Artifact so the web page and Timber share one
-- source of truth; the Artifact could only ever replace its whole
-- document, which loses an edit whenever two writers overlap.
--
-- Generated by rogue-farm-wiki/scripts/build-harvest-board-migration.py
-- Seeded from: C:\Users\Koasm\.claude\projects\C--Users-Koasm-Documents-RogueFamilyFarms\75cb3a02-9cbe-4444-9398-e3d4250d85f7\tool-results\artifact-850ab9ba-1787947900-ab01.html
-- Board state as of: 2026-08-28T20:11:40.667Z

CREATE TABLE IF NOT EXISTS harvest_lots (
  lot_id        TEXT PRIMARY KEY,
  farm          TEXT NOT NULL,
  zone          TEXT NOT NULL,
  cultivar      TEXT NOT NULL,
  cultivar_slug TEXT NOT NULL,
  map           TEXT,
  -- untested | scheduled | cleared | harvesting | drying | supersacked | failed
  stage         TEXT NOT NULL DEFAULT 'untested',
  test_date     TEXT,
  thc           REAL,
  sacks         REAL,
  notes         TEXT,
  docs          TEXT NOT NULL DEFAULT '[]',   -- JSON array of {label, ref}
  updated_at    TEXT,
  -- who last touched it: 'board' | 'timber' | 'migration'. Kept because the
  -- first board-vs-scan disagreement will need to know which side moved.
  updated_by    TEXT
);

CREATE INDEX IF NOT EXISTS idx_harvest_lots_stage ON harvest_lots(stage);
CREATE INDEX IF NOT EXISTS idx_harvest_lots_farm  ON harvest_lots(farm);

-- Seed. INSERT OR IGNORE so re-running never clobbers live board data.
INSERT OR IGNORE INTO harvest_lots
  (lot_id, farm, zone, cultivar, cultivar_slug, map, stage,
   test_date, thc, sacks, notes, updated_by)
VALUES
  ('gary-z14-lifter', 'Gary', 'Z14', 'Lifter', 'lifter', 'gary-z14-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('gary-z14-sour-lifter', 'Gary', 'Z14', 'Sour Lifter', 'sour-lifter', 'gary-z14-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('gary-z15-lifter', 'Gary', 'Z15', 'Lifter', 'lifter', 'gary-z15-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('gary-z15-sour-lifter', 'Gary', 'Z15', 'Sour Lifter', 'sour-lifter', 'gary-z15-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('gary-z16-sour-lifter', 'Gary', 'Z16', 'Sour Lifter', 'sour-lifter', 'gary-z16-sour-lifter.png', 'scheduled', NULL, NULL, NULL, NULL, 'migration'),
  ('gary-z17-sour-lifter', 'Gary', 'Z17', 'Sour Lifter', 'sour-lifter', 'gary-z17-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('gary-z18-sour-lifter', 'Gary', 'Z18', 'Sour Lifter', 'sour-lifter', 'gary-z18-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('gary-z19-lifter', 'Gary', 'Z19', 'Lifter', 'lifter', 'gary-z19-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('gary-z20-lifter', 'Gary', 'Z20', 'Lifter', 'lifter', 'gary-z20-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('gary-z21-lifter', 'Gary', 'Z21', 'Lifter', 'lifter', 'gary-z21-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-1-angel-cake', 'McLoughlin', 'Zone 1', 'Angel Cake', 'angel-cake', 'mcloughlin-z1-angel-cake.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-1-critical-berries', 'McLoughlin', 'Zone 1', 'Critical Berries', 'critical-berries', 'mcloughlin-z1-critical-berries.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-1-legendary-og', 'McLoughlin', 'Zone 1', 'Legendary OG', 'legendary-og', 'mcloughlin-z1-legendary-og.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-1-peytons-strawberries', 'McLoughlin', 'Zone 1', 'Peyton''s Strawberries', 'peytons-strawberries', 'mcloughlin-z1-peyton-s-strawberries.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-1-platinum-delicata', 'McLoughlin', 'Zone 1', 'Platinum Delicata', 'platinum-delicata', 'mcloughlin-z1-platinum-delicata.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-2-angel-cake', 'McLoughlin', 'Zone 2', 'Angel Cake', 'angel-cake', 'mcloughlin-z2-angel-cake.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-2-daiquiri-factory', 'McLoughlin', 'Zone 2', 'Daiquiri Factory', 'daiquiri-factory', 'mcloughlin-z2-daiquiri-factory.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-2-gmo-gas', 'McLoughlin', 'Zone 2', 'GMO Gas', 'gmo-gas', 'mcloughlin-z2-gmo-gas.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-2-goat-butter', 'McLoughlin', 'Zone 2', 'Goat Butter', 'goat-butter', 'mcloughlin-z2-goat-butter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-2-king-kush', 'McLoughlin', 'Zone 2', 'King Kush', 'king-kush', 'mcloughlin-z2-king-kush.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-2-lavender-bc', 'McLoughlin', 'Zone 2', 'Lavender BC', 'lavender-bc', 'mcloughlin-z2-lavender-bc.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-2-lavender-snowcone', 'McLoughlin', 'Zone 2', 'Lavender Snowcone', 'lavender-snowcone', 'mcloughlin-z2-lavender-snowcone.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-2-platinum-india', 'McLoughlin', 'Zone 2', 'Platinum India', 'platinum-india', 'mcloughlin-z2-platinum-india.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-2-smelly-jelly', 'McLoughlin', 'Zone 2', 'Smelly Jelly', 'smelly-jelly', 'mcloughlin-z2-smelly-jelly.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-2-tropicana-cherry', 'McLoughlin', 'Zone 2', 'Tropicana Cherry', 'tropicana-cherry', 'mcloughlin-z2-tropicana-cherry.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-3-animal-muffins', 'McLoughlin', 'Zone 3', 'Animal Muffins', 'animal-muffins', 'mcloughlin-z3-animal-muffins.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-3-forbidden', 'McLoughlin', 'Zone 3', 'Forbidden', 'forbidden', 'mcloughlin-z3-forbidden.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-3-runtz', 'McLoughlin', 'Zone 3', 'Runtz', 'runtz', 'mcloughlin-z3-runtz.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-3-runtz-bravo', 'McLoughlin', 'Zone 3', 'Runtz Bravo', 'runtz-bravo', 'mcloughlin-z3-runtz-bravo.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-3-sour-diesel', 'McLoughlin', 'Zone 3', 'Sour Diesel', 'sour-diesel', 'mcloughlin-z3-sour-diesel.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-3-strawberry-doughnuts', 'McLoughlin', 'Zone 3', 'Strawberry Doughnuts', 'strawberry-doughnuts', 'mcloughlin-z3-strawberry-doughnuts.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-4-cream-cake', 'McLoughlin', 'Zone 4', 'Cream Cake', 'cream-cake', 'mcloughlin-z4-cream-cake.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-4-gmo-belly', 'McLoughlin', 'Zone 4', 'GMO Belly', 'gmo-belly', 'mcloughlin-z4-gmo-belly.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-4-king-kush', 'McLoughlin', 'Zone 4', 'King Kush', 'king-kush', 'mcloughlin-z4-king-kush.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-4-kush-mintz', 'McLoughlin', 'Zone 4', 'Kush Mintz', 'kush-mintz', 'mcloughlin-z4-kush-mintz.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-4-sour-lifter', 'McLoughlin', 'Zone 4', 'Sour Lifter', 'sour-lifter', 'mcloughlin-z4-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('mcloughlin-zone-4-sour-suver-haze', 'McLoughlin', 'Zone 4', 'Sour Suver Haze', 'sour-suver-haze', 'mcloughlin-z4-sour-suver-haze.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z1-sour-lifter', 'Rogue', 'Z1', 'Sour Lifter', 'sour-lifter', 'rogue-z1-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z2-sour-lifter', 'Rogue', 'Z2', 'Sour Lifter', 'sour-lifter', 'rogue-z2-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z3-sour-lifter', 'Rogue', 'Z3', 'Sour Lifter', 'sour-lifter', 'rogue-z3-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z4-sour-lifter', 'Rogue', 'Z4', 'Sour Lifter', 'sour-lifter', 'rogue-z4-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z5-sour-lifter', 'Rogue', 'Z5', 'Sour Lifter', 'sour-lifter', 'rogue-z5-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z6-sour-lifter', 'Rogue', 'Z6', 'Sour Lifter', 'sour-lifter', 'rogue-z6-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z7-sour-lifter', 'Rogue', 'Z7', 'Sour Lifter', 'sour-lifter', 'rogue-z7-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z8-blue-pineapple-quik', 'Rogue', 'Z8', 'Blue Pineapple Quik', 'blue-pineapple-quik', 'rogue-z8-blue-pineapple-quik.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z8-lemon', 'Rogue', 'Z8', 'Lemon', 'lemon', 'rogue-z8-lemon.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z8-orange-pineapple-quik', 'Rogue', 'Z8', 'Orange Pineapple Quik', 'orange-pineapple-quik', 'rogue-z8-orange-pineapple-quik.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z8-platinum', 'Rogue', 'Z8', 'Platinum', 'platinum', 'rogue-z8-platinum.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z8-platinum-m-a4', 'Rogue', 'Z8', 'Platinum M A4', 'platinum-m-a4', 'rogue-z8-platinum-m-a4.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z8-rainbow-cake', 'Rogue', 'Z8', 'Rainbow Cake', 'rainbow-cake', 'rogue-z8-rainbow-cake.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z8-rainbow-gmo-quik', 'Rogue', 'Z8', 'Rainbow GMO Quik', 'rainbow-gmo-quik', 'rogue-z8-rainbow-gmo-quik.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z9-sour-lifter', 'Rogue', 'Z9', 'Sour Lifter', 'sour-lifter', 'rogue-z9-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-animal-muffins', 'Rogue', 'Z10', 'Animal Muffins', 'animal-muffins', 'rogue-z10-animal-muffins.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-demi-glaze', 'Rogue', 'Z10', 'Demi Glaze', 'demi-glaze', 'rogue-z10-demi-glaze.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-gmo-belly', 'Rogue', 'Z10', 'GMO Belly', 'gmo-belly', 'rogue-z10-gmo-belly.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-key-lime-cbg', 'Rogue', 'Z10', 'Key Lime CBG', 'key-lime-cbg', 'rogue-z10-key-lime-cbg.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-lemon', 'Rogue', 'Z10', 'Lemon', 'lemon', 'rogue-z10-lemon.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-limey-lifter', 'Rogue', 'Z10', 'Limey Lifter', 'limey-lifter', 'rogue-z10-limey-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-mandarin-chocolate', 'Rogue', 'Z10', 'Mandarin Chocolate', 'mandarin-chocolate', 'rogue-z10-mandarin-chocolate.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-mountain-apple', 'Rogue', 'Z10', 'Mountain Apple', 'mountain-apple', 'rogue-z10-mountain-apple.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-puff-pastries', 'Rogue', 'Z10', 'Puff Pastries', 'puff-pastries', 'rogue-z10-puff-pastries.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-rocket-sauce', 'Rogue', 'Z10', 'Rocket Sauce', 'rocket-sauce', 'rogue-z10-rocket-sauce.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-snickerdoodle', 'Rogue', 'Z10', 'Snickerdoodle', 'snickerdoodle', 'rogue-z10-snickerdoodle.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-spruce-dough', 'Rogue', 'Z10', 'Spruce Dough', 'spruce-dough', 'rogue-z10-spruce-dough.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-strawberry-cream', 'Rogue', 'Z10', 'Strawberry Cream', 'strawberry-cream', 'rogue-z10-strawberry-cream.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-strawberry-doughnuts', 'Rogue', 'Z10', 'Strawberry Doughnuts', 'strawberry-doughnuts', 'rogue-z10-strawberry-doughnuts.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z10-tahitian', 'Rogue', 'Z10', 'Tahitian', 'tahitian', 'rogue-z10-tahitian.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z11-sour-lifter', 'Rogue', 'Z11', 'Sour Lifter', 'sour-lifter', 'rogue-z11-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z12-sour-lifter', 'Rogue', 'Z12', 'Sour Lifter', 'sour-lifter', 'rogue-z12-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-z13-sour-lifter', 'Rogue', 'Z13', 'Sour Lifter', 'sour-lifter', 'rogue-z13-sour-lifter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-gh1a-legendary-banana-mac', 'Rogue', 'GH1A', 'Legendary Banana Mac', 'legendary-banana-mac', NULL, 'supersacked', NULL, NULL, NULL, 'Harvested 2026-08-12 with the rest of the house; house now empty.
Pre-harvest test passed (the GH1 submission went in 2026-08-11) but the date and Total THC for this bed are not recorded in the wiki yet — fill them in and link the COA.', 'migration'),
  ('rogue-gh1b-strawberry-doughnuts', 'Rogue', 'GH1B', 'Strawberry Doughnuts', 'strawberry-doughnuts', NULL, 'supersacked', NULL, NULL, NULL, 'Harvested 2026-08-12 with the rest of the house; house now empty.
Pre-harvest test passed (the GH1 submission went in 2026-08-11) but the date and Total THC for this bed are not recorded in the wiki yet — fill them in and link the COA.', 'migration'),
  ('rogue-gh1c-animal-muffins', 'Rogue', 'GH1C', 'Animal Muffins', 'animal-muffins', NULL, 'failed', '2026-08-11', 0.7, NULL, 'FAILED pre-harvest at 0.7% Total THC — over the limit.
Destroyed under ODA supervision 2026-08-17: 360 sq ft, ~2,700 plants. Witness Hemp Inspector Michael Williams; signed Jacob Fisher (RFF).
Filed as CWD-2026-01.', 'migration'),
  ('rogue-gh1d-gravy-train', 'Rogue', 'GH1D', 'Gravy Train', 'gravy-train', NULL, 'supersacked', NULL, NULL, NULL, 'Harvested 2026-08-12 with the rest of the house; house now empty.
Pre-harvest test passed (the GH1 submission went in 2026-08-11) but the date and Total THC for this bed are not recorded in the wiki yet — fill them in and link the COA.', 'migration'),
  ('rogue-gh1e-purple-snowman', 'Rogue', 'GH1E', 'Purple Snowman', 'purple-snowman', NULL, 'supersacked', NULL, NULL, NULL, 'Harvested 2026-08-12 with the rest of the house; house now empty.
Pre-harvest test passed (the GH1 submission went in 2026-08-11) but the date and Total THC for this bed are not recorded in the wiki yet — fill them in and link the COA.', 'migration'),
  ('rogue-r1-animal-muffins', 'Rogue', 'R1', 'Animal Muffins', 'animal-muffins', 'rogue-r1-animal-muffins.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-r1-orange-fritter', 'Rogue', 'R1', 'Orange Fritter', 'orange-fritter', 'rogue-r1-orange-fritter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-r1-purple-snowman', 'Rogue', 'R1', 'Purple Snowman', 'purple-snowman', 'rogue-r1-purple-snowman.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-r1-sauciere', 'Rogue', 'R1', 'Sauciere', 'sauciere', 'rogue-r1-sauciere.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-r1-strawberry-doughnuts', 'Rogue', 'R1', 'Strawberry Doughnuts', 'strawberry-doughnuts', 'rogue-r1-strawberry-doughnuts.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-r1-strawberry-fritter', 'Rogue', 'R1', 'Strawberry Fritter', 'strawberry-fritter', 'rogue-r1-strawberry-fritter.png', 'untested', NULL, NULL, NULL, NULL, 'migration'),
  ('rogue-r1-strawberry-sauce', 'Rogue', 'R1', 'Strawberry Sauce', 'strawberry-sauce', 'rogue-r1-strawberry-sauce.png', 'untested', NULL, NULL, NULL, NULL, 'migration');

-- Document links carried over from the board.
UPDATE harvest_lots SET docs = '[{"label": "CWD-2026-01 (signed ODA form)", "ref": "raw/compliance/2026/Rogue-Family-Farms-CWD-2026-08-17.pdf"}]' WHERE lot_id = 'rogue-gh1c-animal-muffins';
